# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Kristelle\Documents\CCC151-Group Project\CCC151-Group--BH-Management-System\UI_Files\AddRoom.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(413, 249)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(10, 10, 391, 231))
        self.frame.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"border: 2px solid #800000;\n"
"border-radius: 6px;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(10, 10, 371, 61))
        self.frame_3.setStyleSheet("background-color: #800000;  /* Maroon background */\n"
"                border: 1px solid #660000;  /* Darker maroon border */\n"
"                border-radius: 4px;\n"
"                padding: 5px;\n"
"                font-family: \'Times New Roman\', serif;  /* Formal font */\n"
"                font-size: 14px;\n"
"                color: white;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(150, 10, 81, 41))
        self.label_2.setStyleSheet("background-color: rgb(250, 255, 242);\n"
"border: 1px solid #660000;\n"
"border-radius: 4px;\n"
"padding: 5px;\n"
"font-family: \'Cal Sans\', sans-serif;\n"
"font-weight: 700;\n"
"font-style: normal;\n"
"font-size: 20px;\n"
"color: #800000;\n"
"text-align: center;\n"
"vertical-align: middle;\n"
"\n"
"")
        self.label_2.setObjectName("label_2")
        self.RoomNumberLineEdit = QtWidgets.QLineEdit(self.frame)
        self.RoomNumberLineEdit.setGeometry(QtCore.QRect(20, 110, 111, 21))
        self.RoomNumberLineEdit.setObjectName("RoomNumberLineEdit")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 111, 16))
        self.label_3.setStyleSheet("background: none;\n"
"    border: none;\n"
"    color: #800000;\n"
"    font-family: \'Cal Sans\', sans-serif;\n"
"    font-weight: 700;\n"
"    font-style: normal;\n"
"    font-size: 14px;")
        self.label_3.setObjectName("label_3")
        self.PriceLineEdit = QtWidgets.QLineEdit(self.frame)
        self.PriceLineEdit.setGeometry(QtCore.QRect(140, 110, 111, 21))
        self.PriceLineEdit.setObjectName("PriceLineEdit")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(180, 90, 61, 16))
        self.label_4.setStyleSheet("background: none;\n"
"    border: none;\n"
"    color: #800000;\n"
"    font-family: \'Cal Sans\', sans-serif;\n"
"    font-weight: 700;\n"
"    font-style: normal;\n"
"    font-size: 14px;")
        self.label_4.setObjectName("label_4")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(210, 140, 131, 16))
        self.label_9.setStyleSheet("background: none;\n"
"    border: none;\n"
"    color: #800000;\n"
"    font-family: \'Cal Sans\', sans-serif;\n"
"    font-weight: 700;\n"
"    font-style: normal;\n"
"    font-size: 14px;")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(270, 90, 81, 16))
        self.label_10.setStyleSheet("background: none;\n"
"    border: none;\n"
"    color: #800000;\n"
"    font-family: \'Cal Sans\', sans-serif;\n"
"    font-weight: 700;\n"
"    font-style: normal;\n"
"    font-size: 14px;")
        self.label_10.setObjectName("label_10")
        self.AddpushButton = QtWidgets.QPushButton(self.frame)
        self.AddpushButton.setGeometry(QtCore.QRect(290, 190, 93, 28))
        self.AddpushButton.setStyleSheet("background-color: #388E3C; /* Darker green */\n"
"color: white;\n"
"font-family: \"Cal Sans\", sans-serif;\n"
"font-weight: 700; /* Bold */\n"
"font-size: 16px;\n"
"border: none;\n"
"border-radius: 4px;\n"
"padding: 6px 12px;\n"
"")
        self.AddpushButton.setObjectName("AddpushButton")
        self.CancelpushButton = QtWidgets.QPushButton(self.frame)
        self.CancelpushButton.setGeometry(QtCore.QRect(190, 190, 93, 28))
        self.CancelpushButton.setStyleSheet("background: rgb(157, 157, 157);\n"
"color: white;\n"
"font-family: \'Cal Sans\', sans-serif;\n"
"font-weight: 500;\n"
"font-style: normal;\n"
"font-size: 12px;\n"
"border: 1px solid rgb(169, 169, 169);\n"
"")
        self.CancelpushButton.setObjectName("CancelpushButton")
        self.TenantSexComboBox = QtWidgets.QComboBox(self.frame)
        self.TenantSexComboBox.setGeometry(QtCore.QRect(260, 110, 101, 22))
        self.TenantSexComboBox.setObjectName("TenantSexComboBox")
        self.NoOfOccupantsComboBox = QtWidgets.QComboBox(self.frame)
        self.NoOfOccupantsComboBox.setGeometry(QtCore.QRect(210, 160, 121, 22))
        self.NoOfOccupantsComboBox.setObjectName("NoOfOccupantsComboBox")
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(40, 140, 161, 16))
        self.label_13.setStyleSheet("background: none;\n"
"    border: none;\n"
"    color: #800000;\n"
"    font-family: \'Cal Sans\', sans-serif;\n"
"    font-weight: 700;\n"
"    font-style: normal;\n"
"    font-size: 14px;")
        self.label_13.setObjectName("label_13")
        self.MaxNoOccupantsLineEdit = QtWidgets.QLineEdit(self.frame)
        self.MaxNoOccupantsLineEdit.setGeometry(QtCore.QRect(60, 160, 111, 21))
        self.MaxNoOccupantsLineEdit.setObjectName("MaxNoOccupantsLineEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Room"))
        self.label_3.setText(_translate("Dialog", "Room Number"))
        self.label_4.setText(_translate("Dialog", "Price"))
        self.label_9.setText(_translate("Dialog", "No. of Occupants"))
        self.label_10.setText(_translate("Dialog", "Tenant Sex"))
        self.AddpushButton.setText(_translate("Dialog", "Add"))
        self.CancelpushButton.setText(_translate("Dialog", "Cancel"))
        self.label_13.setText(_translate("Dialog", "Max No. of Occupants"))
