# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Kristelle\Documents\CCC151-Group Project\CCC151-Group--BH-Management-System\UI_Files\EditTenant.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(450, 350)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(10, 10, 431, 331))
        self.frame.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"border: 2px solid #800000;\n"
"border-radius: 6px;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(20, 10, 391, 61))
        self.frame_3.setStyleSheet("background-color: #800000;  /* Maroon background */\n"
"                border: 1px solid #660000;  /* Darker maroon border */\n"
"                border-radius: 4px;\n"
"                padding: 5px;\n"
"                font-family: \'Times New Roman\', serif;  /* Formal font */\n"
"                font-size: 14px;\n"
"                color: white;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(110, 10, 161, 41))
        self.label_2.setStyleSheet("background-color: rgb(250, 255, 242);\n"
"border: 1px solid #660000;\n"
"border-radius: 4px;\n"
"padding: 5px;\n"
"font-family: \'Cal Sans\', sans-serif;\n"
"font-weight: 700;\n"
"font-style: normal;\n"
"font-size: 20px;\n"
"color: #800000;\n"
"text-align: center;\n"
"vertical-align: middle;\n"
"\n"
"")
        self.label_2.setObjectName("label_2")
        self.TenantIDLineEdit = QtWidgets.QLineEdit(self.frame)
        self.TenantIDLineEdit.setGeometry(QtCore.QRect(310, 110, 101, 22))
        self.TenantIDLineEdit.setObjectName("TenantIDLineEdit")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(310, 90, 81, 16))
        self.label.setStyleSheet("background: none;\n"
"    border: none;\n"
"    color: #800000;\n"
"    font-family: \'Cal Sans\', sans-serif;\n"
"    font-weight: 700;\n"
"    font-style: normal;\n"
"    font-size: 14px;")
        self.label.setObjectName("label")
        self.FirstNameLineEdit = QtWidgets.QLineEdit(self.frame)
        self.FirstNameLineEdit.setGeometry(QtCore.QRect(20, 110, 271, 21))
        self.FirstNameLineEdit.setObjectName("FirstNameLineEdit")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 91, 16))
        self.label_3.setStyleSheet("background: none;\n"
"    border: none;\n"
"    color: #800000;\n"
"    font-family: \'Cal Sans\', sans-serif;\n"
"    font-weight: 700;\n"
"    font-style: normal;\n"
"    font-size: 14px;")
        self.label_3.setObjectName("label_3")
        self.MiddleNameLineEdit = QtWidgets.QLineEdit(self.frame)
        self.MiddleNameLineEdit.setGeometry(QtCore.QRect(20, 160, 271, 21))
        self.MiddleNameLineEdit.setObjectName("MiddleNameLineEdit")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(20, 140, 91, 16))
        self.label_4.setStyleSheet("background: none;\n"
"    border: none;\n"
"    color: #800000;\n"
"    font-family: \'Cal Sans\', sans-serif;\n"
"    font-weight: 700;\n"
"    font-style: normal;\n"
"    font-size: 14px;")
        self.label_4.setObjectName("label_4")
        self.LastNameLineEdit = QtWidgets.QLineEdit(self.frame)
        self.LastNameLineEdit.setGeometry(QtCore.QRect(20, 210, 271, 21))
        self.LastNameLineEdit.setObjectName("LastNameLineEdit")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(20, 190, 91, 16))
        self.label_9.setStyleSheet("background: none;\n"
"    border: none;\n"
"    color: #800000;\n"
"    font-family: \'Cal Sans\', sans-serif;\n"
"    font-weight: 700;\n"
"    font-style: normal;\n"
"    font-size: 14px;")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(310, 140, 81, 16))
        self.label_10.setStyleSheet("background: none;\n"
"    border: none;\n"
"    color: #800000;\n"
"    font-family: \'Cal Sans\', sans-serif;\n"
"    font-weight: 700;\n"
"    font-style: normal;\n"
"    font-size: 14px;")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(310, 190, 41, 16))
        self.label_11.setStyleSheet("background: none;\n"
"    border: none;\n"
"    color: #800000;\n"
"    font-family: \'Cal Sans\', sans-serif;\n"
"    font-weight: 700;\n"
"    font-style: normal;\n"
"    font-size: 14px;")
        self.label_11.setObjectName("label_11")
        self.PhoneNumberLineEdit = QtWidgets.QLineEdit(self.frame)
        self.PhoneNumberLineEdit.setGeometry(QtCore.QRect(230, 260, 181, 21))
        self.PhoneNumberLineEdit.setObjectName("PhoneNumberLineEdit")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(230, 240, 111, 16))
        self.label_12.setStyleSheet("background: none;\n"
"    border: none;\n"
"    color: #800000;\n"
"    font-family: \'Cal Sans\', sans-serif;\n"
"    font-weight: 700;\n"
"    font-style: normal;\n"
"    font-size: 14px;")
        self.label_12.setObjectName("label_12")
        self.label_21 = QtWidgets.QLabel(self.frame)
        self.label_21.setGeometry(QtCore.QRect(20, 240, 111, 16))
        self.label_21.setStyleSheet("background: none;\n"
"    border: none;\n"
"    color: #800000;\n"
"    font-family: \'Cal Sans\', sans-serif;\n"
"    font-weight: 700;\n"
"    font-style: normal;\n"
"    font-size: 14px;")
        self.label_21.setObjectName("label_21")
        self.EmailLineEdit = QtWidgets.QLineEdit(self.frame)
        self.EmailLineEdit.setGeometry(QtCore.QRect(20, 260, 191, 21))
        self.EmailLineEdit.setObjectName("EmailLineEdit")
        self.RoomNoComboBox = QtWidgets.QComboBox(self.frame)
        self.RoomNoComboBox.setGeometry(QtCore.QRect(310, 160, 101, 22))
        self.RoomNoComboBox.setObjectName("RoomNoComboBox")
        self.SexComboBox = QtWidgets.QComboBox(self.frame)
        self.SexComboBox.setGeometry(QtCore.QRect(310, 210, 101, 22))
        self.SexComboBox.setObjectName("SexComboBox")
        self.UpdatepushButton = QtWidgets.QPushButton(self.frame)
        self.UpdatepushButton.setGeometry(QtCore.QRect(320, 290, 93, 31))
        self.UpdatepushButton.setStyleSheet("background-color: #388E3C; /* Darker green */\n"
"color: white;\n"
"font-family: \"Cal Sans\", sans-serif;\n"
"font-weight: 700; /* Bold */\n"
"font-size: 16px;\n"
"border: none;\n"
"border-radius: 4px;\n"
"padding: 6px 12px;\n"
"")
        self.UpdatepushButton.setObjectName("UpdatepushButton")
        self.CancelpushButton = QtWidgets.QPushButton(self.frame)
        self.CancelpushButton.setGeometry(QtCore.QRect(220, 290, 93, 31))
        self.CancelpushButton.setStyleSheet("background: rgb(157, 157, 157);\n"
"color: white;\n"
"font-family: \'Cal Sans\', sans-serif;\n"
"font-weight: 500;\n"
"font-style: normal;\n"
"font-size: 12px;\n"
"border: 1px solid rgb(169, 169, 169);\n"
"")
        self.CancelpushButton.setObjectName("CancelpushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Tenant Profile"))
        self.label.setText(_translate("Dialog", "Tenant ID"))
        self.label_3.setText(_translate("Dialog", "First Name"))
        self.label_4.setText(_translate("Dialog", "Middle Name"))
        self.label_9.setText(_translate("Dialog", "Last Name"))
        self.label_10.setText(_translate("Dialog", "Room No."))
        self.label_11.setText(_translate("Dialog", "Sex"))
        self.label_12.setText(_translate("Dialog", "Phone Number"))
        self.label_21.setText(_translate("Dialog", "Email"))
        self.UpdatepushButton.setText(_translate("Dialog", "Update"))
        self.CancelpushButton.setText(_translate("Dialog", "Cancel"))
