# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Kristelle\Documents\CCC151-Group Project\CCC151-Group--BH-Management-System\UI_Files\EditECEmbed.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(449, 384)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 0, 431, 331))
        self.frame.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"border: 2px solid #800000;\n"
"border-radius: 6px;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(20, 10, 391, 61))
        self.frame_3.setStyleSheet("background-color: #800000;  /* Maroon background */\n"
"                border: 1px solid #660000;  /* Darker maroon border */\n"
"                border-radius: 4px;\n"
"                padding: 5px;\n"
"                font-family: \'Times New Roman\', serif;  /* Formal font */\n"
"                font-size: 14px;\n"
"                color: white;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(80, 10, 221, 41))
        self.label_2.setStyleSheet("background-color: rgb(250, 255, 242);\n"
"border: 1px solid #660000;\n"
"border-radius: 4px;\n"
"padding: 5px;\n"
"font-family: \'Cal Sans\', sans-serif;\n"
"font-weight: 700;\n"
"font-style: normal;\n"
"font-size: 20px;\n"
"color: #800000;\n"
"text-align: center;\n"
"vertical-align: middle;\n"
"\n"
"")
        self.label_2.setObjectName("label_2")
        self.ContactIDLineEdit = QtWidgets.QLineEdit(self.frame)
        self.ContactIDLineEdit.setGeometry(QtCore.QRect(310, 110, 101, 22))
        self.ContactIDLineEdit.setObjectName("ContactIDLineEdit")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(310, 90, 81, 16))
        self.label.setStyleSheet("background: none;\n"
"    border: none;\n"
"    color: #800000;\n"
"    font-family: \'Cal Sans\', sans-serif;\n"
"    font-weight: 700;\n"
"    font-style: normal;\n"
"    font-size: 14px;")
        self.label.setObjectName("label")
        self.FirstNameLineEdit = QtWidgets.QLineEdit(self.frame)
        self.FirstNameLineEdit.setGeometry(QtCore.QRect(20, 110, 271, 21))
        self.FirstNameLineEdit.setObjectName("FirstNameLineEdit")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 91, 16))
        self.label_3.setStyleSheet("background: none;\n"
"    border: none;\n"
"    color: #800000;\n"
"    font-family: \'Cal Sans\', sans-serif;\n"
"    font-weight: 700;\n"
"    font-style: normal;\n"
"    font-size: 14px;")
        self.label_3.setObjectName("label_3")
        self.MibbleNameLineEdit = QtWidgets.QLineEdit(self.frame)
        self.MibbleNameLineEdit.setGeometry(QtCore.QRect(20, 160, 271, 21))
        self.MibbleNameLineEdit.setObjectName("MibbleNameLineEdit")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(20, 140, 91, 16))
        self.label_4.setStyleSheet("background: none;\n"
"    border: none;\n"
"    color: #800000;\n"
"    font-family: \'Cal Sans\', sans-serif;\n"
"    font-weight: 700;\n"
"    font-style: normal;\n"
"    font-size: 14px;")
        self.label_4.setObjectName("label_4")
        self.LastNameLineEdit = QtWidgets.QLineEdit(self.frame)
        self.LastNameLineEdit.setGeometry(QtCore.QRect(20, 210, 271, 21))
        self.LastNameLineEdit.setObjectName("LastNameLineEdit")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(20, 190, 91, 16))
        self.label_9.setStyleSheet("background: none;\n"
"    border: none;\n"
"    color: #800000;\n"
"    font-family: \'Cal Sans\', sans-serif;\n"
"    font-weight: 700;\n"
"    font-style: normal;\n"
"    font-size: 14px;")
        self.label_9.setObjectName("label_9")
        self.PhoneNumberLineEdit = QtWidgets.QLineEdit(self.frame)
        self.PhoneNumberLineEdit.setGeometry(QtCore.QRect(220, 260, 191, 21))
        self.PhoneNumberLineEdit.setObjectName("PhoneNumberLineEdit")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(220, 240, 111, 16))
        self.label_12.setStyleSheet("background: none;\n"
"    border: none;\n"
"    color: #800000;\n"
"    font-family: \'Cal Sans\', sans-serif;\n"
"    font-weight: 700;\n"
"    font-style: normal;\n"
"    font-size: 14px;")
        self.label_12.setObjectName("label_12")
        self.label_21 = QtWidgets.QLabel(self.frame)
        self.label_21.setGeometry(QtCore.QRect(20, 240, 111, 16))
        self.label_21.setStyleSheet("background: none;\n"
"    border: none;\n"
"    color: #800000;\n"
"    font-family: \'Cal Sans\', sans-serif;\n"
"    font-weight: 700;\n"
"    font-style: normal;\n"
"    font-size: 14px;")
        self.label_21.setObjectName("label_21")
        self.RelationshipLineEdit = QtWidgets.QLineEdit(self.frame)
        self.RelationshipLineEdit.setGeometry(QtCore.QRect(20, 260, 191, 21))
        self.RelationshipLineEdit.setObjectName("RelationshipLineEdit")
        self.UpdatepushButton = QtWidgets.QPushButton(self.frame)
        self.UpdatepushButton.setGeometry(QtCore.QRect(320, 290, 93, 28))
        self.UpdatepushButton.setStyleSheet("background-color: #388E3C; /* Darker green */\n"
"color: white;\n"
"font-family: \"Cal Sans\", sans-serif;\n"
"font-weight: 700; /* Bold */\n"
"font-size: 16px;\n"
"border: none;\n"
"border-radius: 4px;\n"
"padding: 6px 12px;\n"
"")
        self.UpdatepushButton.setObjectName("UpdatepushButton")
        self.CancelpushButton = QtWidgets.QPushButton(self.frame)
        self.CancelpushButton.setGeometry(QtCore.QRect(220, 290, 93, 28))
        self.CancelpushButton.setStyleSheet("background: rgb(157, 157, 157);\n"
"color: white;\n"
"font-family: \'Cal Sans\', sans-serif;\n"
"font-weight: 500;\n"
"font-style: normal;\n"
"font-size: 12px;\n"
"border: 1px solid rgb(169, 169, 169);\n"
"")
        self.CancelpushButton.setObjectName("CancelpushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 449, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Emergency Contact"))
        self.label.setText(_translate("MainWindow", "Contact ID"))
        self.label_3.setText(_translate("MainWindow", "First Name"))
        self.label_4.setText(_translate("MainWindow", "Middle Name"))
        self.label_9.setText(_translate("MainWindow", "Last Name"))
        self.label_12.setText(_translate("MainWindow", "Phone Number"))
        self.label_21.setText(_translate("MainWindow", "Relationship"))
        self.UpdatepushButton.setText(_translate("MainWindow", "Update"))
        self.CancelpushButton.setText(_translate("MainWindow", "Cancel"))
