# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Kristelle\Documents\CCC151-Group Project\CCC151-Group--BH-Management-System\UI_Files\EditPayment.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(311, 300)
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setGeometry(QtCore.QRect(10, 10, 291, 281))
        self.frame_2.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"border: 2px solid #800000;\n"
"border-radius: 6px;\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setGeometry(QtCore.QRect(10, 10, 271, 61))
        self.frame_5.setStyleSheet("background-color: #800000;  /* Maroon background */\n"
"                border: 1px solid #660000;  /* Darker maroon border */\n"
"                border-radius: 4px;\n"
"                padding: 5px;\n"
"                font-family: \'Times New Roman\', serif;  /* Formal font */\n"
"                font-size: 14px;\n"
"                color: white;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_11 = QtWidgets.QLabel(self.frame_5)
        self.label_11.setGeometry(QtCore.QRect(80, 10, 111, 41))
        self.label_11.setStyleSheet("background-color: rgb(250, 255, 242);\n"
"border: 1px solid #660000;\n"
"border-radius: 4px;\n"
"padding: 5px;\n"
"font-family: \'Cal Sans\', sans-serif;\n"
"font-weight: 700;\n"
"font-style: normal;\n"
"font-size: 20px;\n"
"color: #800000;\n"
"text-align: center;\n"
"vertical-align: middle;\n"
"\n"
"")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(20, 90, 111, 16))
        self.label_12.setStyleSheet("background: none;\n"
"    border: none;\n"
"    color: #800000;\n"
"    font-family: \'Cal Sans\', sans-serif;\n"
"    font-weight: 700;\n"
"    font-style: normal;\n"
"    font-size: 14px;")
        self.label_12.setObjectName("label_12")
        self.PaymentAmountLineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.PaymentAmountLineEdit.setGeometry(QtCore.QRect(20, 160, 121, 21))
        self.PaymentAmountLineEdit.setObjectName("PaymentAmountLineEdit")
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        self.label_13.setGeometry(QtCore.QRect(20, 140, 121, 20))
        self.label_13.setStyleSheet("background: none;\n"
"    border: none;\n"
"    color: #800000;\n"
"    font-family: \'Cal Sans\', sans-serif;\n"
"    font-weight: 700;\n"
"    font-style: normal;\n"
"    font-size: 14px;")
        self.label_13.setObjectName("label_13")
        self.label_15 = QtWidgets.QLabel(self.frame_2)
        self.label_15.setGeometry(QtCore.QRect(160, 90, 121, 20))
        self.label_15.setStyleSheet("background: none;\n"
"    border: none;\n"
"    color: #800000;\n"
"    font-family: \'Cal Sans\', sans-serif;\n"
"    font-weight: 700;\n"
"    font-style: normal;\n"
"    font-size: 14px;")
        self.label_15.setObjectName("label_15")
        self.UpdatepushButton = QtWidgets.QPushButton(self.frame_2)
        self.UpdatepushButton.setGeometry(QtCore.QRect(150, 240, 93, 28))
        self.UpdatepushButton.setStyleSheet("background-color: #388E3C; /* Darker green */\n"
"color: white;\n"
"font-family: \"Cal Sans\", sans-serif;\n"
"font-weight: 700; /* Bold */\n"
"font-size: 16px;\n"
"border: none;\n"
"border-radius: 4px;\n"
"padding: 6px 12px;\n"
"")
        self.UpdatepushButton.setObjectName("UpdatepushButton")
        self.CancelpushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.CancelpushButton_3.setGeometry(QtCore.QRect(50, 240, 93, 28))
        self.CancelpushButton_3.setStyleSheet("background: rgb(157, 157, 157);\n"
"color: white;\n"
"font-family: \'Cal Sans\', sans-serif;\n"
"font-weight: 500;\n"
"font-style: normal;\n"
"font-size: 12px;\n"
"border: 1px solid rgb(169, 169, 169);\n"
"")
        self.CancelpushButton_3.setObjectName("CancelpushButton_3")
        self.PayingTenantIDComboBox = QtWidgets.QComboBox(self.frame_2)
        self.PayingTenantIDComboBox.setGeometry(QtCore.QRect(160, 110, 111, 22))
        self.PayingTenantIDComboBox.setObjectName("PayingTenantIDComboBox")
        self.label_14 = QtWidgets.QLabel(self.frame_2)
        self.label_14.setGeometry(QtCore.QRect(160, 140, 121, 20))
        self.label_14.setStyleSheet("background: none;\n"
"    border: none;\n"
"    color: #800000;\n"
"    font-family: \'Cal Sans\', sans-serif;\n"
"    font-weight: 700;\n"
"    font-style: normal;\n"
"    font-size: 14px;")
        self.label_14.setObjectName("label_14")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(90, 190, 111, 16))
        self.label_10.setStyleSheet("background: none;\n"
"    border: none;\n"
"    color: #800000;\n"
"    font-family: \'Cal Sans\', sans-serif;\n"
"    font-weight: 700;\n"
"    font-style: normal;\n"
"    font-size: 14px;")
        self.label_10.setObjectName("label_10")
        self.PaymentStatusComboBox = QtWidgets.QComboBox(self.frame_2)
        self.PaymentStatusComboBox.setGeometry(QtCore.QRect(90, 210, 111, 22))
        self.PaymentStatusComboBox.setObjectName("PaymentStatusComboBox")
        self.RoomNumberComboBox = QtWidgets.QComboBox(self.frame_2)
        self.RoomNumberComboBox.setGeometry(QtCore.QRect(20, 110, 111, 22))
        self.RoomNumberComboBox.setObjectName("RoomNumberComboBox")
        self.dateEdit = QtWidgets.QDateEdit(self.frame_2)
        self.dateEdit.setGeometry(QtCore.QRect(160, 160, 111, 22))
        self.dateEdit.setObjectName("dateEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_11.setText(_translate("Dialog", "Payment"))
        self.label_12.setText(_translate("Dialog", "Room Number"))
        self.label_13.setText(_translate("Dialog", "Payment Amount"))
        self.label_15.setText(_translate("Dialog", "Paying Tenant ID"))
        self.UpdatepushButton.setText(_translate("Dialog", "Update"))
        self.CancelpushButton_3.setText(_translate("Dialog", "Cancel"))
        self.label_14.setText(_translate("Dialog", "Payment Date"))
        self.label_10.setText(_translate("Dialog", "Payment Status"))
