# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Kristelle\Documents\CCC151-Group Project\CCC151-Group--BH-Management-System\UI_Files\AddRent.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(300, 299)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(10, 10, 281, 281))
        self.frame.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"border: 2px solid #800000;\n"
"border-radius: 6px;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(10, 10, 261, 61))
        self.frame_3.setStyleSheet("background-color: #800000;  /* Maroon background */\n"
"                border: 1px solid #660000;  /* Darker maroon border */\n"
"                border-radius: 4px;\n"
"                padding: 5px;\n"
"                font-family: \'Times New Roman\', serif;  /* Formal font */\n"
"                font-size: 14px;\n"
"                color: white;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(90, 10, 81, 41))
        self.label_2.setStyleSheet("background-color: rgb(250, 255, 242);\n"
"border: 1px solid #660000;\n"
"border-radius: 4px;\n"
"padding: 5px;\n"
"font-family: \'Cal Sans\', sans-serif;\n"
"font-weight: 700;\n"
"font-style: normal;\n"
"font-size: 20px;\n"
"color: #800000;\n"
"text-align: center;\n"
"vertical-align: middle;\n"
"\n"
"")
        self.label_2.setObjectName("label_2")
        self.AddpushButton = QtWidgets.QPushButton(self.frame)
        self.AddpushButton.setGeometry(QtCore.QRect(140, 240, 93, 28))
        self.AddpushButton.setStyleSheet("background-color: #388E3C; /* Darker green */\n"
"color: white;\n"
"font-family: \"Cal Sans\", sans-serif;\n"
"font-weight: 700; /* Bold */\n"
"font-size: 16px;\n"
"border: none;\n"
"border-radius: 4px;\n"
"padding: 6px 12px;\n"
"")
        self.AddpushButton.setObjectName("AddpushButton")
        self.CancelpushButton = QtWidgets.QPushButton(self.frame)
        self.CancelpushButton.setGeometry(QtCore.QRect(40, 240, 93, 28))
        self.CancelpushButton.setStyleSheet("background: rgb(157, 157, 157);\n"
"color: white;\n"
"font-family: \'Cal Sans\', sans-serif;\n"
"font-weight: 500;\n"
"font-style: normal;\n"
"font-size: 12px;\n"
"border: 1px solid rgb(169, 169, 169);\n"
"")
        self.CancelpushButton.setObjectName("CancelpushButton")
        self.MoveStatuscomboBox = QtWidgets.QComboBox(self.frame)
        self.MoveStatuscomboBox.setGeometry(QtCore.QRect(20, 160, 111, 22))
        self.MoveStatuscomboBox.setObjectName("MoveStatuscomboBox")
        self.MoveInDateEdit = QtWidgets.QDateEdit(self.frame)
        self.MoveInDateEdit.setGeometry(QtCore.QRect(150, 160, 110, 22))
        self.MoveInDateEdit.setObjectName("MoveInDateEdit")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(20, 140, 111, 16))
        self.label_10.setStyleSheet("background: none;\n"
"    border: none;\n"
"    color: #800000;\n"
"    font-family: \'Cal Sans\', sans-serif;\n"
"    font-weight: 700;\n"
"    font-style: normal;\n"
"    font-size: 14px;")
        self.label_10.setObjectName("label_10")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(150, 140, 111, 16))
        self.label_5.setStyleSheet("background: none;\n"
"    border: none;\n"
"    color: #800000;\n"
"    font-family: \'Cal Sans\', sans-serif;\n"
"    font-weight: 700;\n"
"    font-style: normal;\n"
"    font-size: 14px;")
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(10, 90, 131, 16))
        self.label_4.setStyleSheet("background: none;\n"
"    border: none;\n"
"    color: #800000;\n"
"    font-family: \'Cal Sans\', sans-serif;\n"
"    font-weight: 700;\n"
"    font-style: normal;\n"
"    font-size: 14px;")
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(150, 90, 101, 16))
        self.label_3.setStyleSheet("background: none;\n"
"    border: none;\n"
"    color: #800000;\n"
"    font-family: \'Cal Sans\', sans-serif;\n"
"    font-weight: 700;\n"
"    font-style: normal;\n"
"    font-size: 14px;")
        self.label_3.setObjectName("label_3")
        self.MoveOutDateEdit = QtWidgets.QDateEdit(self.frame)
        self.MoveOutDateEdit.setGeometry(QtCore.QRect(80, 210, 110, 22))
        self.MoveOutDateEdit.setObjectName("MoveOutDateEdit")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(80, 190, 111, 16))
        self.label_6.setStyleSheet("background: none;\n"
"    border: none;\n"
"    color: #800000;\n"
"    font-family: \'Cal Sans\', sans-serif;\n"
"    font-weight: 700;\n"
"    font-style: normal;\n"
"    font-size: 14px;")
        self.label_6.setObjectName("label_6")
        self.RoomNumberComboBox = QtWidgets.QComboBox(self.frame)
        self.RoomNumberComboBox.setGeometry(QtCore.QRect(150, 110, 111, 22))
        self.RoomNumberComboBox.setObjectName("RoomNumberComboBox")
        self.RentingTenantComboBox = QtWidgets.QComboBox(self.frame)
        self.RentingTenantComboBox.setGeometry(QtCore.QRect(20, 110, 111, 22))
        self.RentingTenantComboBox.setObjectName("RentingTenantComboBox")
        # self.RentingTenantLineEdit = QtWidgets.QLineEdit(self.frame)
        # self.RentingTenantLineEdit.setGeometry(QtCore.QRect(20, 110, 111, 21))
        # self.RentingTenantLineEdit.setObjectName("RentingTenantLineEdit")
        self.RentingTenantIDComboBox = QtWidgets.QComboBox(self.frame)
        self.RentingTenantIDComboBox.setGeometry(QtCore.QRect(20, 110, 111, 21))
        self.RentingTenantIDComboBox.setObjectName("RentingTenantIDComboBox")
        # self.RoomNumberLineEdit = QtWidgets.QLineEdit(self.frame)
        # self.RoomNumberLineEdit.setGeometry(QtCore.QRect(150, 110, 111, 21))
        # self.RoomNumberLineEdit.setObjectName("RoomNumberLineEdit")
        self.RoomNoComboBox = QtWidgets.QComboBox(self.frame)
        self.RoomNoComboBox.setGeometry(QtCore.QRect(150, 110, 111, 21))
        self.RoomNoComboBox.setObjectName("RoomNoComboBox")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Rent"))
        self.label_2.setText(_translate("Dialog", "Rent"))
        self.AddpushButton.setText(_translate("Dialog", "Add"))
        self.CancelpushButton.setText(_translate("Dialog", "Cancel"))
        self.label_10.setText(_translate("Dialog", "Status"))
        self.label_5.setText(_translate("Dialog", "Move-in Date"))
        self.label_4.setText(_translate("Dialog", "Renting Tenant ID"))
        self.label_3.setText(_translate("Dialog", "Room Number"))
        self.label_6.setText(_translate("Dialog", "Move-out Date"))
