# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Kristelle\Documents\CCC151-Group Project\CCC151-Group--BH-Management-System\UI_Files\AddTenant.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QSpacerItem, QSizePolicy

class Ui_Dialog(object):
        def setupUi(self, Dialog):

# =========================
#        BASE FRAME
# ==========
                Dialog.setObjectName("Dialog")
                Dialog.resize(675, 450)
                self.mainFrame = QtWidgets.QFrame(Dialog)
                self.mainFrame.setGeometry(QtCore.QRect(10, 10, 658, 431))
                self.mainFrame.setStyleSheet(   "background-color: rgb(240, 240, 240);\n"
                                                "border: 2px solid #800000;\n"
                                                "border-radius: 6px;\n"
                                                )
                self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.mainFrame.setObjectName("mainFrame")
                self.HeaderFrame = QtWidgets.QFrame(self.mainFrame)
                self.HeaderFrame.setGeometry(QtCore.QRect(20, 10, 618, 61))
                self.HeaderFrame.setStyleSheet( "background-color: #800000;  /* Maroon background */\n"
                                                "border: 1px solid #660000;  /* Darker maroon border */\n"
                                                "border-radius: 4px;\n"
                                                "padding: 5px;\n"
                                                "font-family: \'Times New Roman\', serif;  /* Formal font */\n"
                                                "font-size: 14px;\n"
                                                "color: white;"
                                                )
                self.HeaderFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.HeaderFrame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.HeaderFrame.setObjectName("HeaderFrame")

                self.EMInfoLabel = QtWidgets.QLabel(self.HeaderFrame)
                self.EMInfoLabel.setGeometry(QtCore.QRect(120, 10, 388, 41))
                self.EMInfoLabel.setStyleSheet(     "background-color: rgb(250, 255, 242);\n"
                                                        "border: 1px solid #660000;\n"
                                                        "border-radius: 4px;\n"
                                                        "padding: 5px;\n"
                                                        "font-family: \'Cal Sans\', sans-serif;\n"
                                                        "font-weight: 700;\n"
                                                        "font-style: normal;\n"
                                                        "font-size: 20px;\n"
                                                        "color: #800000;\n"
                                                        "text-align: center;\n"
                                                        "vertical-align: middle;\n"
                                                        )
                self.EMInfoLabel.setObjectName("EMInfoLabel")
                self.EMInfoLabel.setAlignment(Qt.AlignCenter)

# ==========
#        BASE FRAME
# =========================



# =========================
#        EM INFO
# ==========

                self.InfoFrame = QtWidgets.QFrame(self.mainFrame)
                self.InfoFrame.setGeometry(QtCore.QRect(20, 90, 618, 310))
                self.InfoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.InfoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.InfoFrame.setObjectName("InfoFrame")

                self.gridFrame = QtWidgets.QGridLayout(self.InfoFrame)
                self.gridFrame.setContentsMargins(5, 5, 5, 5)  
                self.gridFrame.setHorizontalSpacing(4) 
                self.gridFrame.setAlignment(QtCore.Qt.AlignCenter)
                self.InfoFrame.setLayout(self.gridFrame)

                # ===========
                # Base info
                self.NameLabel = QtWidgets.QLabel(self.InfoFrame)
                self.NameLabel.setStyleSheet(   "background: none;\n"
                                                "border: none;\n"
                                                "color: #800000;\n"
                                                "font-family: \'Cal Sans\', sans-serif;\n"
                                                "font-weight: 700;\n"
                                                "font-style: normal;\n"
                                                "font-size: 14px;")
                self.NameLabel.setObjectName("NameLabel")

                self.NameLine = QtWidgets.QLineEdit(self.InfoFrame)
                self.NameLine.setObjectName("NameLine")
                self.NameLine.setReadOnly(True)

                self.ContactIDLabel = QtWidgets.QLabel(self.InfoFrame)
                self.ContactIDLabel.setStyleSheet(    "background: none;\n"
                                                "border: none;\n"
                                                "color: #800000;\n"
                                                "font-family: \'Cal Sans\', sans-serif;\n"
                                                "font-weight: 700;\n"
                                                "font-style: normal;\n"
                                                "font-size: 14px;")
                self.ContactIDLabel.setObjectName("ContactIDLabel")

                self.ContactIDLine = QtWidgets.QLineEdit(self.InfoFrame)
                self.ContactIDLine.setObjectName("ContactIDLine")
                self.ContactIDLine.setReadOnly(True)
                # Base info
                # ===========

                # ===========
                # Contact info
                self.PhonNumLabel = QtWidgets.QLabel(self.InfoFrame)
                self.PhonNumLabel.setStyleSheet("background: none;\n"
                                                "border: none;\n"
                                                "color: #800000;\n"
                                                "font-family: \'Cal Sans\', sans-serif;\n"
                                                "font-weight: 700;\n"
                                                "font-style: normal;\n"
                                                "font-size: 14px;")
                self.PhonNumLabel.setObjectName("PhonNumLabel")

                self.PhoneLine = QtWidgets.QLineEdit(self.InfoFrame)
                self.PhoneLine.setObjectName("PhoneLine")
                self.PhoneLine.setReadOnly(True)

                self.RelationshipLabel = QtWidgets.QLabel(self.InfoFrame)
                self.RelationshipLabel.setStyleSheet("background: none;\n"
                                                "border: none;\n"
                                                "color: #800000;\n"
                                                "font-family: \'Cal Sans\', sans-serif;\n"
                                                "font-weight: 700;\n"
                                                "font-style: normal;\n"
                                                "font-size: 14px;")
                self.RelationshipLabel.setObjectName("RelationshipLabel")

                self.RelationshipLine = QtWidgets.QLineEdit(self.InfoFrame)
                self.RelationshipLine.setObjectName("RelationshipLine")
                self.RelationshipLine.setReadOnly(True)
                # Contact info
                # ===========

                # ===========
                # Tenant info
                self.TenantNameLabel = QtWidgets.QLabel(self.InfoFrame)
                self.TenantNameLabel.setStyleSheet(     "background: none;\n"
                                                        "border: none;\n"
                                                        "color: #800000;\n"
                                                        "font-family: \'Cal Sans\', sans-serif;\n"
                                                        "font-weight: 700;\n"
                                                        "font-style: normal;\n"
                                                        "font-size: 14px;")
                self.TenantNameLabel.setObjectName("TenantNameLabel")

                self.TenantNameLine = QtWidgets.QLineEdit(self.InfoFrame)
                self.TenantNameLine.setObjectName("TenantNameLine")
                self.TenantNameLine.setReadOnly(True)
                
                self.EMTenantIDLabel = QtWidgets.QLabel(self.InfoFrame)
                self.EMTenantIDLabel.setStyleSheet(  "background: none;\n"
                                                "border: none;\n"
                                                "color: #800000;\n"
                                                "font-family: \'Cal Sans\', sans-serif;\n"
                                                "font-weight: 700;\n"
                                                "font-style: normal;\n"
                                                "font-size: 14px;")
                self.EMTenantIDLabel.setObjectName("EMTenantIDLabel")

                self.EMTenantIDLine = QtWidgets.QLineEdit(self.InfoFrame)
                self.EMTenantIDLine.setObjectName("EMTenantIDLine")
                self.EMTenantIDLine.setReadOnly(True)
                # Tenant info
                # ===========

                # =========
                # Layout

                self.gridFrame.addItem(QSpacerItem(20, 320, QSizePolicy.Minimum, QSizePolicy.Expanding), 0, 0, 4)

                self.gridFrame.addWidget(self.NameLabel,        1, 0)
                self.gridFrame.addWidget(self.NameLine,         1, 1, 1, 4)

                self.gridFrame.addWidget(self.ContactIDLabel,   2, 0)
                self.gridFrame.addWidget(self.ContactIDLine,    2, 1)

                self.gridFrame.addWidget(self.PhonNumLabel,     2, 2)
                self.gridFrame.addWidget(self.PhoneLine,        2, 3, 1, 2)

                self.gridFrame.addWidget(self.RelationshipLabel,3, 0)
                self.gridFrame.addWidget(self.RelationshipLine, 3, 1, 1, 2)

                self.gridFrame.addItem(QSpacerItem(20, 500, QSizePolicy.Minimum, QSizePolicy.Expanding), 4, 0, 4)

                self.gridFrame.addWidget(self.TenantNameLabel,  5, 0)
                self.gridFrame.addWidget(self.TenantNameLine,   5, 1, 1, 4)

                self.gridFrame.addWidget(self.EMTenantIDLabel,  6, 0)
                self.gridFrame.addWidget(self.EMTenantIDLine,   6, 1)

                # Layout
                # =========


# ==========
#         EM INFO
# =========================

                self.retranslateUi(Dialog)
                QtCore.QMetaObject.connectSlotsByName(Dialog)   

        def retranslateUi(self, Dialog):
                _translate = QtCore.QCoreApplication.translate
                Dialog.setWindowTitle(_translate(       "Dialog", "Dialog"))
                self.EMInfoLabel.setText(_translate(    "Dialog", "Emergency Contact Profile"))
                self.NameLabel.setText(_translate(      "Dialog", "Emergency Contact Name: "))
                self.ContactIDLabel.setText(_translate( "Dialog", "Emergency Contact ID: "))
                self.PhonNumLabel.setText(_translate(   "Dialog", "Phone Number: "))
                self.EMTenantIDLabel.setText(_translate("Dialog", "Emergency Contact: "))
                self.TenantNameLabel.setText(_translate("Dialog", "Tenant Name: "))
                self.EMTenantIDLabel.setText(_translate("Dialog", "Tenant ID: "))
                self.RelationshipLabel.setText(_translate("Dialog","Relationship: "))

