# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Kristelle\Documents\CCC151-Group Project\CCC151-Group--BH-Management-System\UI_Files\AddTenant.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QSpacerItem, QSizePolicy

class Ui_Dialog(object):
        def setupUi(self, Dialog):

# =========================
#        BASE FRAME
# ==========
                Dialog.setObjectName("Dialog")
                Dialog.resize(675, 450)
                self.mainFrame = QtWidgets.QFrame(Dialog)
                self.mainFrame.setGeometry(QtCore.QRect(10, 10, 658, 431))
                self.mainFrame.setStyleSheet(   "background-color: rgb(240, 240, 240);\n"
                                                "border: 2px solid #800000;\n"
                                                "border-radius: 6px;\n"
                                                )
                self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.mainFrame.setObjectName("mainFrame")
                self.HeaderFrame = QtWidgets.QFrame(self.mainFrame)
                self.HeaderFrame.setGeometry(QtCore.QRect(20, 10, 618, 61))
                self.HeaderFrame.setStyleSheet( "background-color: #800000;  /* Maroon background */\n"
                                                "border: 1px solid #660000;  /* Darker maroon border */\n"
                                                "border-radius: 4px;\n"
                                                "padding: 5px;\n"
                                                "font-family: \'Times New Roman\', serif;  /* Formal font */\n"
                                                "font-size: 14px;\n"
                                                "color: white;"
                                                )
                self.HeaderFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.HeaderFrame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.HeaderFrame.setObjectName("HeaderFrame")

                self.PayInfoLabel = QtWidgets.QLabel(self.HeaderFrame)
                self.PayInfoLabel.setGeometry(QtCore.QRect(120, 10, 388, 41))
                self.PayInfoLabel.setStyleSheet(     "background-color: rgb(250, 255, 242);\n"
                                                        "border: 1px solid #660000;\n"
                                                        "border-radius: 4px;\n"
                                                        "padding: 5px;\n"
                                                        "font-family: \'Cal Sans\', sans-serif;\n"
                                                        "font-weight: 700;\n"
                                                        "font-style: normal;\n"
                                                        "font-size: 20px;\n"
                                                        "color: #800000;\n"
                                                        "text-align: center;\n"
                                                        "vertical-align: middle;\n"
                                                        )
                self.PayInfoLabel.setObjectName("PayInfoLabel")
                self.PayInfoLabel.setAlignment(Qt.AlignCenter)

# ==========
#        BASE FRAME
# =========================



# =========================
#      PAY INFO
# ==========

                self.InfoFrame = QtWidgets.QFrame(self.mainFrame)
                self.InfoFrame.setGeometry(QtCore.QRect(20, 90, 618, 310))
                self.InfoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.InfoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.InfoFrame.setObjectName("InfoFrame")

                self.gridFrame = QtWidgets.QGridLayout(self.InfoFrame)
                self.gridFrame.setContentsMargins(5, 5, 5, 5)  
                self.gridFrame.setHorizontalSpacing(4) 
                self.gridFrame.setAlignment(QtCore.Qt.AlignCenter)
                self.InfoFrame.setLayout(self.gridFrame)

                # ===========
                # Base info
                self.PayIDLabel = QtWidgets.QLabel(self.InfoFrame)
                self.PayIDLabel.setStyleSheet(   "background: none;\n"
                                                "border: none;\n"
                                                "color: #800000;\n"
                                                "font-family: \'Cal Sans\', sans-serif;\n"
                                                "font-weight: 700;\n"
                                                "font-style: normal;\n"
                                                "font-size: 14px;")
                self.PayIDLabel.setObjectName("PayIDLabel")

                self.PayIDLine = QtWidgets.QLineEdit(self.InfoFrame)
                self.PayIDLine.setObjectName("PayIDLine")
                self.PayIDLine.setReadOnly(True)

                self.PayTenLabel = QtWidgets.QLabel(self.InfoFrame)
                self.PayTenLabel.setStyleSheet(    "background: none;\n"
                                                "border: none;\n"
                                                "color: #800000;\n"
                                                "font-family: \'Cal Sans\', sans-serif;\n"
                                                "font-weight: 700;\n"
                                                "font-style: normal;\n"
                                                "font-size: 14px;")
                self.PayTenLabel.setObjectName("PayTenLabel")

                self.PayTenLine = QtWidgets.QLineEdit(self.InfoFrame)
                self.PayTenLine.setObjectName("PayTenLine")
                self.PayTenLine.setReadOnly(True)

                self.PayRoomLabel = QtWidgets.QLabel(self.InfoFrame)
                self.PayRoomLabel.setStyleSheet("background: none;\n"
                                                "border: none;\n"
                                                "color: #800000;\n"
                                                "font-family: \'Cal Sans\', sans-serif;\n"
                                                "font-weight: 700;\n"
                                                "font-style: normal;\n"
                                                "font-size: 14px;")
                self.PayRoomLabel.setObjectName("PayRoomLabel")

                self.PayRoomLine = QtWidgets.QLineEdit(self.InfoFrame)
                self.PayRoomLine.setObjectName("PayRoomLine")
                self.PayRoomLine.setReadOnly(True)
                # Base info
                # ===========

                # ===========
                # Contact info
                self.PayTenNameLabel = QtWidgets.QLabel(self.InfoFrame)
                self.PayTenNameLabel.setStyleSheet(    "background: none;\n"
                                                "border: none;\n"
                                                "color: #800000;\n"
                                                "font-family: \'Cal Sans\', sans-serif;\n"
                                                "font-weight: 700;\n"
                                                "font-style: normal;\n"
                                                "font-size: 14px;")
                self.PayTenNameLabel.setObjectName("PayTenNameLabel")

                self.PayTenNameLine = QtWidgets.QLineEdit(self.InfoFrame)
                self.PayTenNameLine.setObjectName("PayTenNameLine")
                self.PayTenNameLine.setReadOnly(True)

                self.PayTenNumLabel = QtWidgets.QLabel(self.InfoFrame)
                self.PayTenNumLabel.setStyleSheet(    "background: none;\n"
                                                "border: none;\n"
                                                "color: #800000;\n"
                                                "font-family: \'Cal Sans\', sans-serif;\n"
                                                "font-weight: 700;\n"
                                                "font-style: normal;\n"
                                                "font-size: 14px;")
                self.PayTenNumLabel.setObjectName("PayTenNameLabel")

                self.PayTenNumLine = QtWidgets.QLineEdit(self.InfoFrame)
                self.PayTenNumLine.setObjectName("PayTenNumLine")
                self.PayTenNumLine.setReadOnly(True)

                self.PayTenIDLabel = QtWidgets.QLabel(self.InfoFrame)
                self.PayTenIDLabel.setStyleSheet(    "background: none;\n"
                                                "border: none;\n"
                                                "color: #800000;\n"
                                                "font-family: \'Cal Sans\', sans-serif;\n"
                                                "font-weight: 700;\n"
                                                "font-style: normal;\n"
                                                "font-size: 14px;")
                self.PayTenIDLabel.setObjectName("PayTenIDLabel")

                self.PayTenIDLine = QtWidgets.QLineEdit(self.InfoFrame)
                self.PayTenIDLine.setObjectName("PayTenIDLine")
                self.PayTenIDLine.setReadOnly(True)
                # Contact info
                # ===========

                # ===========
                # Rents info
                
                self.RentDurLabel = QtWidgets.QLabel(self.InfoFrame)
                self.RentDurLabel.setStyleSheet(     "background: none;\n"
                                                        "border: none;\n"
                                                        "color: #800000;\n"
                                                        "font-family: \'Cal Sans\', sans-serif;\n"
                                                        "font-weight: 700;\n"
                                                        "font-style: normal;\n"
                                                        "font-size: 14px;")
                self.RentDurLabel.setObjectName("RentDurLabel")

                self.RentDurLine = QtWidgets.QLineEdit(self.InfoFrame)
                self.RentDurLine.setObjectName("RentDurLine")
                self.RentDurLine.setReadOnly(True)
                
                self.MoveStatusLabel = QtWidgets.QLabel(self.InfoFrame)
                self.MoveStatusLabel.setStyleSheet(     "background: none;\n"
                                                        "border: none;\n"
                                                        "color: #800000;\n"
                                                        "font-family: \'Cal Sans\', sans-serif;\n"
                                                        "font-weight: 700;\n"
                                                        "font-style: normal;\n"
                                                        "font-size: 14px;")
                self.MoveStatusLabel.setObjectName("MoveStatusLabel")

                self.MoveLine = QtWidgets.QLineEdit(self.InfoFrame)
                self.MoveLine.setObjectName("MoveLine")
                self.MoveLine.setReadOnly(True)
                # Rents info
                # ===========

                # ===========
                # Pays info
                self.PaymStatusLabel = QtWidgets.QLabel(self.InfoFrame)
                self.PaymStatusLabel.setStyleSheet(     "background: none;\n"
                                                        "border: none;\n"
                                                        "color: #800000;\n"
                                                        "font-family: \'Cal Sans\', sans-serif;\n"
                                                        "font-weight: 700;\n"
                                                        "font-style: normal;\n"
                                                        "font-size: 14px;")
                self.PaymStatusLabel.setObjectName("PaymStatusLabel")

                self.PayLine = QtWidgets.QLineEdit(self.InfoFrame)
                self.PayLine.setObjectName("PayLine")
                self.PayLine.setReadOnly(True)

                self.PaidLabel = QtWidgets.QLabel(self.InfoFrame)
                self.PaidLabel.setStyleSheet(     "background: none;\n"
                                                        "border: none;\n"
                                                        "color: #800000;\n"
                                                        "font-family: \'Cal Sans\', sans-serif;\n"
                                                        "font-weight: 700;\n"
                                                        "font-style: normal;\n"
                                                        "font-size: 14px;")
                self.PaidLabel.setObjectName("PaidLabel")

                self.PaidLine = QtWidgets.QLineEdit(self.InfoFrame)
                self.PaidLine.setObjectName("PaidLine")
                self.PaidLine.setReadOnly(True)

                self.SpecPdLabel = QtWidgets.QLabel(self.InfoFrame)
                self.SpecPdLabel.setStyleSheet(     "background: none;\n"
                                                        "border: none;\n"
                                                        "color: #800000;\n"
                                                        "font-family: \'Cal Sans\', sans-serif;\n"
                                                        "font-weight: 700;\n"
                                                        "font-style: normal;\n"
                                                        "font-size: 14px;")
                self.SpecPdLabel.setObjectName("SpecPdLabel")

                self.SpecPaidLine = QtWidgets.QLineEdit(self.InfoFrame)
                self.SpecPaidLine.setObjectName("SpecPaidLine")
                self.SpecPaidLine.setReadOnly(True)

                self.PaymLabel = QtWidgets.QLabel(self.InfoFrame)
                self.PaymLabel.setStyleSheet(     "background: none;\n"
                                                        "border: none;\n"
                                                        "color: #800000;\n"
                                                        "font-family: \'Cal Sans\', sans-serif;\n"
                                                        "font-weight: 700;\n"
                                                        "font-style: normal;\n"
                                                        "font-size: 14px;")
                self.PaymLabel.setObjectName("PaymLabel")

                self.PaymLine = QtWidgets.QDateEdit(self.InfoFrame)
                self.PaymLine.setObjectName("PaymLine")
                self.PaymLine.setDisabled(True)

                self.RemainingLabel = QtWidgets.QLabel(self.InfoFrame)
                self.RemainingLabel.setStyleSheet(     "background: none;\n"
                                                        "border: none;\n"
                                                        "color: #800000;\n"
                                                        "font-family: \'Cal Sans\', sans-serif;\n"
                                                        "font-weight: 700;\n"
                                                        "font-style: normal;\n"
                                                        "font-size: 14px;")
                self.RemainingLabel.setObjectName("RemainingLabel")

                self.RemainLine = QtWidgets.QLineEdit(self.InfoFrame)
                self.RemainLine.setObjectName("RemainLine")
                self.RemainLine.setReadOnly(True)
                # Pays info
                # ===========

                # =========
                # Layout

                self.gridFrame.addItem(QSpacerItem(20, 150, QSizePolicy.Minimum, QSizePolicy.Expanding), 0, 0, 4)

                self.gridFrame.addWidget(self.PayIDLabel,       1, 0)
                self.gridFrame.addWidget(self.PayIDLine,        1, 1)

                self.gridFrame.addWidget(self.PayTenLabel,      1, 2)
                self.gridFrame.addWidget(self.PayTenLine,       1, 3)

                self.gridFrame.addWidget(self.PayRoomLabel,     1, 4)
                self.gridFrame.addWidget(self.PayRoomLine,      1, 5)

                self.gridFrame.addItem(QSpacerItem(20, 70, QSizePolicy.Minimum, QSizePolicy.Expanding), 2, 0, 4)
                
                self.gridFrame.addWidget(self.RentDurLabel,     3, 0)
                self.gridFrame.addWidget(self.RentDurLine,      3, 1, 1, 2)

                self.gridFrame.addWidget(self.MoveStatusLabel,  3, 3)
                self.gridFrame.addWidget(self.MoveLine,         3, 4, 1, 2)

                self.gridFrame.addWidget(self.SpecPdLabel,      4, 0)
                self.gridFrame.addWidget(self.SpecPaidLine,     4, 1, 1, 2)

                self.gridFrame.addWidget(self.PaymLabel,        4, 3)
                self.gridFrame.addWidget(self.PaymLine,         4, 4, 1, 2)

                self.gridFrame.addWidget(self.PaidLabel,        5, 0)
                self.gridFrame.addWidget(self.PaidLine,         5, 1, 1, 2)

                self.gridFrame.addWidget(self.PaymStatusLabel,  6, 3)
                self.gridFrame.addWidget(self.PayLine,          6, 4, 1, 2)

                self.gridFrame.addWidget(self.RemainingLabel,   6, 0)
                self.gridFrame.addWidget(self.RemainLine,       6, 1, 1, 2)

                self.gridFrame.addItem(QSpacerItem(20, 150, QSizePolicy.Minimum, QSizePolicy.Expanding), 7, 0, 4)
                
                self.gridFrame.addWidget(self.PayTenNameLabel, 8, 0)
                self.gridFrame.addWidget(self.PayTenNameLine,  8, 1, 1, 5)

                self.gridFrame.addWidget(self.PayTenNumLabel,  9, 0)
                self.gridFrame.addWidget(self.PayTenNumLine,   9, 1, 1, 2)
                self.gridFrame.addWidget(self.PayTenIDLabel,   9, 3)
                self.gridFrame.addWidget(self.PayTenIDLine,    9, 4, 1, 2)

                # Layout
                # =========


# ==========
#      PAY INFO
# =========================

                self.retranslateUi(Dialog)
                QtCore.QMetaObject.connectSlotsByName(Dialog)   

        def retranslateUi(self, Dialog):
                _translate = QtCore.QCoreApplication.translate
                Dialog.setWindowTitle(_translate(       "Dialog", "Dialog"))
                self.PayInfoLabel.setText(_translate(   "Dialog", "Payment Profile"))
                self.PayIDLabel.setText(_translate(     "Dialog", "Pay ID: "))
                self.PayTenNameLabel.setText(_translate("Dialog", "Tenant Name: "))
                self.PayTenNumLabel.setText(_translate( "Dialog", "Phone Number: "))
                self.PayTenLabel.setText(_translate(    "Dialog", "Paying Tenant: "))
                self.PayRoomLabel.setText(_translate(   "Dialog", "Paid Room: "))
                self.PaidLabel.setText(_translate(      "Dialog", "Total Paid Amount: "))
                self.PaymLabel.setText(_translate(      "Dialog", "Payment Date: "))
                self.RentDurLabel.setText(_translate(   "Dialog", "Rent Duration: "))
                self.MoveStatusLabel.setText(_translate("Dialog", "Move Status: "))
                self.PaymStatusLabel.setText(_translate("Dialog", "Payment Status: "))
                self.RemainingLabel.setText(_translate( "Dialog", "Remaining Due: "))
                self.SpecPdLabel.setText(_translate(    "Dialog", "Payment Amount: "))

