# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Kristelle\Documents\CCC151-Group Project\CCC151-Group--BH-Management-System\UI_Files\AddTenant.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QSpacerItem, QSizePolicy

class Ui_Dialog(object):
        def setupUi(self, Dialog):

# =========================
#        BASE FRAME
# ==========
                Dialog.setObjectName("Dialog")
                Dialog.resize(675, 450)
                self.mainFrame = QtWidgets.QFrame(Dialog)
                self.mainFrame.setGeometry(QtCore.QRect(10, 10, 658, 431))
                self.mainFrame.setStyleSheet(   "background-color: rgb(240, 240, 240);\n"
                                                "border: 2px solid #800000;\n"
                                                "border-radius: 6px;\n"
                                                )
                self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.mainFrame.setObjectName("mainFrame")
                self.HeaderFrame = QtWidgets.QFrame(self.mainFrame)
                self.HeaderFrame.setGeometry(QtCore.QRect(20, 10, 618, 61))
                self.HeaderFrame.setStyleSheet( "background-color: #800000;  /* Maroon background */\n"
                                                "border: 1px solid #660000;  /* Darker maroon border */\n"
                                                "border-radius: 4px;\n"
                                                "padding: 5px;\n"
                                                "font-family: \'Times New Roman\', serif;  /* Formal font */\n"
                                                "font-size: 14px;\n"
                                                "color: white;"
                                                )
                self.HeaderFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.HeaderFrame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.HeaderFrame.setObjectName("HeaderFrame")

                self.RentInfoLabel = QtWidgets.QLabel(self.HeaderFrame)
                self.RentInfoLabel.setGeometry(QtCore.QRect(120, 10, 388, 41))
                self.RentInfoLabel.setStyleSheet(     "background-color: rgb(250, 255, 242);\n"
                                                        "border: 1px solid #660000;\n"
                                                        "border-radius: 4px;\n"
                                                        "padding: 5px;\n"
                                                        "font-family: \'Cal Sans\', sans-serif;\n"
                                                        "font-weight: 700;\n"
                                                        "font-style: normal;\n"
                                                        "font-size: 20px;\n"
                                                        "color: #800000;\n"
                                                        "text-align: center;\n"
                                                        "vertical-align: middle;\n"
                                                        )
                self.RentInfoLabel.setObjectName("RentInfoLabel")
                self.RentInfoLabel.setAlignment(Qt.AlignCenter)

# ==========
#        BASE FRAME
# =========================



# =========================
#      RENT INFO
# ==========

                self.InfoFrame = QtWidgets.QFrame(self.mainFrame)
                self.InfoFrame.setGeometry(QtCore.QRect(20, 90, 618, 310))
                self.InfoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.InfoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.InfoFrame.setObjectName("InfoFrame")

                self.gridFrame = QtWidgets.QGridLayout(self.InfoFrame)
                self.gridFrame.setContentsMargins(5, 5, 5, 5)  
                self.gridFrame.setHorizontalSpacing(4) 
                self.gridFrame.setAlignment(QtCore.Qt.AlignCenter)
                self.InfoFrame.setLayout(self.gridFrame)

                # ===========
                # Base info
                self.RentIDLabel = QtWidgets.QLabel(self.InfoFrame)
                self.RentIDLabel.setStyleSheet(   "background: none;\n"
                                                "border: none;\n"
                                                "color: #800000;\n"
                                                "font-family: \'Cal Sans\', sans-serif;\n"
                                                "font-weight: 700;\n"
                                                "font-style: normal;\n"
                                                "font-size: 14px;")
                self.RentIDLabel.setObjectName("RentIDLabel")

                self.RentIDLine = QtWidgets.QLineEdit(self.InfoFrame)
                self.RentIDLine.setObjectName("RentIDLine")
                self.RentIDLine.setReadOnly(True)

                self.RentTenLabel = QtWidgets.QLabel(self.InfoFrame)
                self.RentTenLabel.setStyleSheet(    "background: none;\n"
                                                "border: none;\n"
                                                "color: #800000;\n"
                                                "font-family: \'Cal Sans\', sans-serif;\n"
                                                "font-weight: 700;\n"
                                                "font-style: normal;\n"
                                                "font-size: 14px;")
                self.RentTenLabel.setObjectName("RentTenLabel")

                self.RentTenLine = QtWidgets.QLineEdit(self.InfoFrame)
                self.RentTenLine.setObjectName("RentTenLine")
                self.RentTenLine.setReadOnly(True)

                self.RentRoomLabel = QtWidgets.QLabel(self.InfoFrame)
                self.RentRoomLabel.setStyleSheet("background: none;\n"
                                                "border: none;\n"
                                                "color: #800000;\n"
                                                "font-family: \'Cal Sans\', sans-serif;\n"
                                                "font-weight: 700;\n"
                                                "font-style: normal;\n"
                                                "font-size: 14px;")
                self.RentRoomLabel.setObjectName("RentRoomLabel")

                self.RentRoomLine = QtWidgets.QLineEdit(self.InfoFrame)
                self.RentRoomLine.setObjectName("RentRoomLine")
                self.RentRoomLine.setReadOnly(True)
                # Base info
                # ===========

                # ===========
                # Contact info
                self.RentTenNameLabel = QtWidgets.QLabel(self.InfoFrame)
                self.RentTenNameLabel.setStyleSheet(    "background: none;\n"
                                                "border: none;\n"
                                                "color: #800000;\n"
                                                "font-family: \'Cal Sans\', sans-serif;\n"
                                                "font-weight: 700;\n"
                                                "font-style: normal;\n"
                                                "font-size: 14px;")
                self.RentTenNameLabel.setObjectName("RentTenNameLabel")

                self.RentTenNameLine = QtWidgets.QLineEdit(self.InfoFrame)
                self.RentTenNameLine.setObjectName("RentTenNameLine")
                self.RentTenNameLine.setReadOnly(True)

                self.RentTenNumLabel = QtWidgets.QLabel(self.InfoFrame)
                self.RentTenNumLabel.setStyleSheet(    "background: none;\n"
                                                "border: none;\n"
                                                "color: #800000;\n"
                                                "font-family: \'Cal Sans\', sans-serif;\n"
                                                "font-weight: 700;\n"
                                                "font-style: normal;\n"
                                                "font-size: 14px;")
                self.RentTenNumLabel.setObjectName("RentTenNameLabel")

                self.RentTenNumLine = QtWidgets.QLineEdit(self.InfoFrame)
                self.RentTenNumLine.setObjectName("RentTenNumLine")
                self.RentTenNumLine.setReadOnly(True)
                # Contact info
                # ===========

                # ===========
                # Rents info
                self.MoveInLabel = QtWidgets.QLabel(self.InfoFrame)
                self.MoveInLabel.setStyleSheet(  "background: none;\n"
                                                "border: none;\n"
                                                "color: #800000;\n"
                                                "font-family: \'Cal Sans\', sans-serif;\n"
                                                "font-weight: 700;\n"
                                                "font-style: normal;\n"
                                                "font-size: 14px;")
                self.MoveInLabel.setObjectName("MoveInLabel")

                self.MoveInLine = QtWidgets.QDateEdit(self.InfoFrame)
                self.MoveInLine.setObjectName("MoveInLine")
                self.MoveInLine.setDisabled(True)

                self.MoveOutLabel = QtWidgets.QLabel(self.InfoFrame)
                self.MoveOutLabel.setStyleSheet(  "background: none;\n"
                                                "border: none;\n"
                                                "color: #800000;\n"
                                                "font-family: \'Cal Sans\', sans-serif;\n"
                                                "font-weight: 700;\n"
                                                "font-style: normal;\n"
                                                "font-size: 14px;")
                self.MoveOutLabel.setObjectName("MoveOutLabel")

                self.MoveOutLine = QtWidgets.QDateEdit(self.InfoFrame)
                self.MoveOutLine.setObjectName("MoveInLine")
                self.MoveOutLine.setDisabled(True)

                self.RentDurLabel = QtWidgets.QLabel(self.InfoFrame)
                self.RentDurLabel.setStyleSheet(     "background: none;\n"
                                                        "border: none;\n"
                                                        "color: #800000;\n"
                                                        "font-family: \'Cal Sans\', sans-serif;\n"
                                                        "font-weight: 700;\n"
                                                        "font-style: normal;\n"
                                                        "font-size: 14px;")
                self.RentDurLabel.setObjectName("RentDurLabel")

                self.RentDurLine = QtWidgets.QLineEdit(self.InfoFrame)
                self.RentDurLine.setObjectName("RentDurLine")
                self.RentDurLine.setReadOnly(True)
                
                self.MoveStatusLabel = QtWidgets.QLabel(self.InfoFrame)
                self.MoveStatusLabel.setStyleSheet(     "background: none;\n"
                                                        "border: none;\n"
                                                        "color: #800000;\n"
                                                        "font-family: \'Cal Sans\', sans-serif;\n"
                                                        "font-weight: 700;\n"
                                                        "font-style: normal;\n"
                                                        "font-size: 14px;")
                self.MoveStatusLabel.setObjectName("MoveStatusLabel")

                self.MoveLine = QtWidgets.QLineEdit(self.InfoFrame)
                self.MoveLine.setObjectName("MoveLine")
                self.MoveLine.setReadOnly(True)
                # Rents info
                # ===========

                # ===========
                # Pays info
                self.PaymStatusLabel = QtWidgets.QLabel(self.InfoFrame)
                self.PaymStatusLabel.setStyleSheet(     "background: none;\n"
                                                        "border: none;\n"
                                                        "color: #800000;\n"
                                                        "font-family: \'Cal Sans\', sans-serif;\n"
                                                        "font-weight: 700;\n"
                                                        "font-style: normal;\n"
                                                        "font-size: 14px;")
                self.PaymStatusLabel.setObjectName("PaymStatusLabel")

                self.PayLine = QtWidgets.QLineEdit(self.InfoFrame)
                self.PayLine.setObjectName("PayLine")
                self.PayLine.setReadOnly(True)

                self.RemainingLabel = QtWidgets.QLabel(self.InfoFrame)
                self.RemainingLabel.setStyleSheet(     "background: none;\n"
                                                        "border: none;\n"
                                                        "color: #800000;\n"
                                                        "font-family: \'Cal Sans\', sans-serif;\n"
                                                        "font-weight: 700;\n"
                                                        "font-style: normal;\n"
                                                        "font-size: 14px;")
                self.RemainingLabel.setObjectName("RemainingLabel")

                self.RemainLine = QtWidgets.QLineEdit(self.InfoFrame)
                self.RemainLine.setObjectName("RemainLine")
                self.RemainLine.setReadOnly(True)
                # Pays info
                # ===========

                # =========
                # Layout

                self.gridFrame.addItem(QSpacerItem(20, 150, QSizePolicy.Minimum, QSizePolicy.Expanding), 0, 0, 4)

                self.gridFrame.addWidget(self.RentIDLabel,      1, 0)
                self.gridFrame.addWidget(self.RentIDLine,       1, 1)

                self.gridFrame.addWidget(self.RentTenLabel,     1, 2)
                self.gridFrame.addWidget(self.RentTenLine,      1, 3)

                self.gridFrame.addWidget(self.RentRoomLabel,    1, 4)
                self.gridFrame.addWidget(self.RentRoomLine,     1, 5)

                self.gridFrame.addItem(QSpacerItem(20, 150, QSizePolicy.Minimum, QSizePolicy.Expanding), 2, 0, 4)

                self.gridFrame.addWidget(self.MoveInLabel,      3, 0)
                self.gridFrame.addWidget(self.MoveInLine,       3, 1, 1, 2)

                self.gridFrame.addWidget(self.MoveOutLabel,     3, 3)
                self.gridFrame.addWidget(self.MoveOutLine,      3, 4, 1, 2)

                self.gridFrame.addWidget(self.RentDurLabel,     4, 0)
                self.gridFrame.addWidget(self.RentDurLine,      4, 1, 1, 2)

                self.gridFrame.addWidget(self.MoveStatusLabel,  4, 3)
                self.gridFrame.addWidget(self.MoveLine,         4, 4, 1, 2)

                self.gridFrame.addWidget(self.PaymStatusLabel,  5, 3)
                self.gridFrame.addWidget(self.PayLine,          5, 4, 1, 2)

                self.gridFrame.addWidget(self.RemainingLabel,   5, 0)
                self.gridFrame.addWidget(self.RemainLine,       5, 1, 1, 2)

                self.gridFrame.addItem(QSpacerItem(20, 150, QSizePolicy.Minimum, QSizePolicy.Expanding), 6, 0, 4)
                
                self.gridFrame.addWidget(self.RentTenNameLabel, 7, 0)
                self.gridFrame.addWidget(self.RentTenNameLine,  7, 1, 1, 5)

                self.gridFrame.addWidget(self.RentTenNumLabel,  8, 0)
                self.gridFrame.addWidget(self.RentTenNumLine,   8, 1, 1, 5)

                # Layout
                # =========


# ==========
#      RENT INFO
# =========================

                self.retranslateUi(Dialog)
                QtCore.QMetaObject.connectSlotsByName(Dialog)   

        def retranslateUi(self, Dialog):
                _translate = QtCore.QCoreApplication.translate
                Dialog.setWindowTitle(_translate(       "Dialog", "Dialog"))
                self.RentInfoLabel.setText(_translate(  "Dialog", "Rent Profile"))
                self.RentIDLabel.setText(_translate(    "Dialog", "Rent ID: "))
                self.RentTenNameLabel.setText(_translate("Dialog", "Tenant Name: "))
                self.RentTenNumLabel.setText(_translate("Dialog", "Phone Number: "))
                self.RentTenLabel.setText(_translate(   "Dialog", "Renting Tenant: "))
                self.RentRoomLabel.setText(_translate(  "Dialog", "Rented Room: "))
                self.MoveInLabel.setText(_translate(    "Dialog", "Move In Date: "))
                self.MoveOutLabel.setText(_translate(   "Dialog", "Move Out Date: "))
                self.RentDurLabel.setText(_translate(   "Dialog", "Rent Duration: "))
                self.MoveStatusLabel.setText(_translate("Dialog", "Move Status: "))
                self.PaymStatusLabel.setText(_translate("Dialog", "Payment Status: "))
                self.RemainingLabel.setText(_translate( "Dialog", "Remaining Due: "))

