# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Kristelle\Documents\CCC151-Group Project\CCC151-Group--BH-Management-System\UI_Files\AddTenant.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QSpacerItem, QSizePolicy

class Ui_Dialog(object):
        def setupUi(self, Dialog):

# =========================
#        BASE FRAME
# ==========
                Dialog.setObjectName("Dialog")
                Dialog.resize(675, 450)
                self.mainFrame = QtWidgets.QFrame(Dialog)
                self.mainFrame.setGeometry(QtCore.QRect(10, 10, 658, 431))
                self.mainFrame.setStyleSheet(   "background-color: rgb(240, 240, 240);\n"
                                                "border: 2px solid #800000;\n"
                                                "border-radius: 6px;\n"
                                                )
                self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.mainFrame.setObjectName("mainFrame")
                self.HeaderFrame = QtWidgets.QFrame(self.mainFrame)
                self.HeaderFrame.setGeometry(QtCore.QRect(20, 10, 618, 61))
                self.HeaderFrame.setStyleSheet( "background-color: #800000;  /* Maroon background */\n"
                                                "border: 1px solid #660000;  /* Darker maroon border */\n"
                                                "border-radius: 4px;\n"
                                                "padding: 5px;\n"
                                                "font-family: \'Times New Roman\', serif;  /* Formal font */\n"
                                                "font-size: 14px;\n"
                                                "color: white;"
                                                )
                self.HeaderFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.HeaderFrame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.HeaderFrame.setObjectName("HeaderFrame")

                self.RoomInfoLabel = QtWidgets.QLabel(self.HeaderFrame)
                self.RoomInfoLabel.setGeometry(QtCore.QRect(120, 10, 388, 41))
                self.RoomInfoLabel.setStyleSheet(     "background-color: rgb(250, 255, 242);\n"
                                                        "border: 1px solid #660000;\n"
                                                        "border-radius: 4px;\n"
                                                        "padding: 5px;\n"
                                                        "font-family: \'Cal Sans\', sans-serif;\n"
                                                        "font-weight: 700;\n"
                                                        "font-style: normal;\n"
                                                        "font-size: 20px;\n"
                                                        "color: #800000;\n"
                                                        "text-align: center;\n"
                                                        "vertical-align: middle;\n"
                                                        )
                self.RoomInfoLabel.setObjectName("RoomInfoLabel")
                self.RoomInfoLabel.setAlignment(Qt.AlignCenter)

# ==========
#        BASE FRAME
# =========================



# =========================
#      ROOM INFO
# ==========

                self.InfoFrame = QtWidgets.QFrame(self.mainFrame)
                self.InfoFrame.setGeometry(QtCore.QRect(20, 90, 618, 310))
                self.InfoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.InfoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.InfoFrame.setObjectName("InfoFrame")

                self.gridFrame = QtWidgets.QGridLayout(self.InfoFrame)
                self.gridFrame.setContentsMargins(5, 5, 5, 5)  
                self.gridFrame.setHorizontalSpacing(4) 
                self.gridFrame.setAlignment(QtCore.Qt.AlignCenter)
                self.InfoFrame.setLayout(self.gridFrame)

                # ===========
                # Base info
                self.RoomIDLabel = QtWidgets.QLabel(self.InfoFrame)
                self.RoomIDLabel.setStyleSheet(   "background: none;\n"
                                                "border: none;\n"
                                                "color: #800000;\n"
                                                "font-family: \'Cal Sans\', sans-serif;\n"
                                                "font-weight: 700;\n"
                                                "font-style: normal;\n"
                                                "font-size: 14px;")
                self.RoomIDLabel.setObjectName("RoomIDLabel")

                self.RoomIDLine = QtWidgets.QLineEdit(self.InfoFrame)
                self.RoomIDLine.setObjectName("RoomIDLine")
                self.RoomIDLine.setReadOnly(True)

                self.RoomPriceLabel = QtWidgets.QLabel(self.InfoFrame)
                self.RoomPriceLabel.setStyleSheet(   "background: none;\n"
                                                "border: none;\n"
                                                "color: #800000;\n"
                                                "font-family: \'Cal Sans\', sans-serif;\n"
                                                "font-weight: 700;\n"
                                                "font-style: normal;\n"
                                                "font-size: 14px;")
                self.RoomPriceLabel.setObjectName("RoomPriceLabel")

                self.RoomPriceLine = QtWidgets.QLineEdit(self.InfoFrame)
                self.RoomPriceLine.setObjectName("RoomPriceLine")
                self.RoomPriceLine.setReadOnly(True)

                self.CapacityLabel = QtWidgets.QLabel(self.InfoFrame)
                self.CapacityLabel.setStyleSheet(    "background: none;\n"
                                                "border: none;\n"
                                                "color: #800000;\n"
                                                "font-family: \'Cal Sans\', sans-serif;\n"
                                                "font-weight: 700;\n"
                                                "font-style: normal;\n"
                                                "font-size: 14px;")
                self.CapacityLabel.setObjectName("CapacityLabel")

                self.CapacityLine = QtWidgets.QLineEdit(self.InfoFrame)
                self.CapacityLine.setObjectName("CapacityLine")
                self.CapacityLine.setReadOnly(True)
                # Base info
                # ===========

                # ===========
                # Rents info
                self.OccupantsLabel = QtWidgets.QLabel(self.InfoFrame)
                self.OccupantsLabel.setStyleSheet(    "background: none;\n"
                                                "border: none;\n"
                                                "color: #800000;\n"
                                                "font-family: \'Cal Sans\', sans-serif;\n"
                                                "font-weight: 700;\n"
                                                "font-style: normal;\n"
                                                "font-size: 14px;")
                self.OccupantsLabel.setObjectName("OccupantsLabel")

                self.OccupantsLine = QtWidgets.QLineEdit(self.InfoFrame)
                self.OccupantsLine.setObjectName("OccupantsLine")
                self.OccupantsLine.setReadOnly(True)

                self.ContractsLabel = QtWidgets.QLabel(self.InfoFrame)
                self.ContractsLabel.setStyleSheet(    "background: none;\n"
                                                "border: none;\n"
                                                "color: #800000;\n"
                                                "font-family: \'Cal Sans\', sans-serif;\n"
                                                "font-weight: 700;\n"
                                                "font-style: normal;\n"
                                                "font-size: 14px;")
                self.ContractsLabel.setObjectName("ContractsLabel")

                self.ContractsLine = QtWidgets.QLineEdit(self.InfoFrame)
                self.ContractsLine.setObjectName("ContractsLine")
                self.ContractsLine.setReadOnly(True)
                # self.TenantsFrame = QtWidgets.QFrame(self.mainFrame)
                # self.TenantsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                # self.TenantsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
                # self.TenantsFrame.setObjectName("TenantsFrame")

                # self.gridTenantsFrame = QtWidgets.QGridLayout(self.TenantsFrame)
                # self.gridTenantsFrame.setContentsMargins(5, 5, 5, 5)  
                # self.gridTenantsFrame.setHorizontalSpacing(4) 
                # self.gridTenantsFrame.setAlignment(QtCore.Qt.AlignCenter)
                # self.TenantsFrame.setLayout(self.gridTenantsFrame)

                # Rents info
                # ===========

                # ===========
                # Pays info
                self.PaymStatusLabel = QtWidgets.QLabel(self.InfoFrame)
                self.PaymStatusLabel.setStyleSheet(     "background: none;\n"
                                                        "border: none;\n"
                                                        "color: #800000;\n"
                                                        "font-family: \'Cal Sans\', sans-serif;\n"
                                                        "font-weight: 700;\n"
                                                        "font-style: normal;\n"
                                                        "font-size: 14px;")
                self.PaymStatusLabel.setObjectName("PaymStatusLabel")

                self.PayLine = QtWidgets.QLineEdit(self.InfoFrame)
                self.PayLine.setObjectName("PayLine")
                self.PayLine.setReadOnly(True)

                self.RemainingLabel = QtWidgets.QLabel(self.InfoFrame)
                self.RemainingLabel.setStyleSheet(     "background: none;\n"
                                                        "border: none;\n"
                                                        "color: #800000;\n"
                                                        "font-family: \'Cal Sans\', sans-serif;\n"
                                                        "font-weight: 700;\n"
                                                        "font-style: normal;\n"
                                                        "font-size: 14px;")
                self.RemainingLabel.setObjectName("RemainingLabel")

                self.RemainLine = QtWidgets.QLineEdit(self.InfoFrame)
                self.RemainLine.setObjectName("RemainLine")
                self.RemainLine.setReadOnly(True)
                # Pays info
                # ===========

                # =========
                # Layout

                self.gridFrame.addItem(QSpacerItem(20, 300, QSizePolicy.Minimum, QSizePolicy.Expanding), 0, 0, 4)

                self.gridFrame.addWidget(self.RoomIDLabel,      1, 0)
                self.gridFrame.addWidget(self.RoomIDLine,       1, 1)

                self.gridFrame.addWidget(self.RoomPriceLabel,   1, 2)
                self.gridFrame.addWidget(self.RoomPriceLine,    1, 3)

                self.gridFrame.addItem(QSpacerItem(20, 300, QSizePolicy.Minimum, QSizePolicy.Expanding), 2, 0, 4)
                                         
                self.gridFrame.addWidget(self.ContractsLabel,   3, 0)
                self.gridFrame.addWidget(self.ContractsLine,    3, 1)   

                self.gridFrame.addWidget(self.CapacityLabel,    4, 0)
                self.gridFrame.addWidget(self.CapacityLine,     4, 1)

                self.gridFrame.addWidget(self.OccupantsLabel,   4, 2)
                self.gridFrame.addWidget(self.OccupantsLine,    4, 3)

                self.gridFrame.addItem(QSpacerItem(20, 300, QSizePolicy.Minimum, QSizePolicy.Expanding), 6, 0, 4)

                self.gridFrame.addWidget(self.PaymStatusLabel,  6, 0)
                self.gridFrame.addWidget(self.PayLine,          6, 1)

                self.gridFrame.addWidget(self.RemainingLabel,   6, 2)
                self.gridFrame.addWidget(self.RemainLine,       6, 3)
                
                # Layout
                # =========


# ==========
#      ROOM INFO
# =========================

                self.retranslateUi(Dialog)
                QtCore.QMetaObject.connectSlotsByName(Dialog)   

        def retranslateUi(self, Dialog):
                _translate = QtCore.QCoreApplication.translate
                Dialog.setWindowTitle(_translate(       "Dialog", "Dialog"))
                self.RoomInfoLabel.setText(_translate(  "Dialog", "Room Profile"))
                self.RoomIDLabel.setText(_translate(    "Dialog", "Room Number: "))
                self.RoomPriceLabel.setText(_translate( "Dialog", "Price: "))
                self.CapacityLabel.setText(_translate(  "Dialog", "Maximum Capacity: "))
                self.OccupantsLabel.setText(_translate( "Dialog", "Number of Occupants: "))
                self.ContractsLabel.setText(_translate( "Dialog", "Ongoing Contracts: "))
                self.PaymStatusLabel.setText(_translate("Dialog", "Payment Status: "))
                self.RemainingLabel.setText(_translate( "Dialog", "Remaining Due: "))

