# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Kristelle\Documents\CCC151-Group Project\CCC151-Group--BH-Management-System\UI_Files\AddTenant.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt

class Ui_Dialog(object):
        def setupUi(self, Dialog):

# =========================
#        BASE FRAME
# ==========
                Dialog.setObjectName("Dialog")
                Dialog.resize(675, 450)
                self.mainFrame = QtWidgets.QFrame(Dialog)
                self.mainFrame.setGeometry(QtCore.QRect(10, 10, 658, 431))
                self.mainFrame.setStyleSheet(   "background-color: rgb(240, 240, 240);\n"
                                                "border: 2px solid #800000;\n"
                                                "border-radius: 6px;\n"
                                                )
                self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.mainFrame.setObjectName("mainFrame")
                self.HeaderFrame = QtWidgets.QFrame(self.mainFrame)
                self.HeaderFrame.setGeometry(QtCore.QRect(20, 10, 618, 61))
                self.HeaderFrame.setStyleSheet( "background-color: #800000;  /* Maroon background */\n"
                                                "border: 1px solid #660000;  /* Darker maroon border */\n"
                                                "border-radius: 4px;\n"
                                                "padding: 5px;\n"
                                                "font-family: \'Times New Roman\', serif;  /* Formal font */\n"
                                                "font-size: 14px;\n"
                                                "color: white;"
                                                )
                self.HeaderFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.HeaderFrame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.HeaderFrame.setObjectName("HeaderFrame")

                self.TenantInfoLabel = QtWidgets.QLabel(self.HeaderFrame)
                self.TenantInfoLabel.setGeometry(QtCore.QRect(120, 10, 388, 41))
                self.TenantInfoLabel.setStyleSheet(     "background-color: rgb(250, 255, 242);\n"
                                                        "border: 1px solid #660000;\n"
                                                        "border-radius: 4px;\n"
                                                        "padding: 5px;\n"
                                                        "font-family: \'Cal Sans\', sans-serif;\n"
                                                        "font-weight: 700;\n"
                                                        "font-style: normal;\n"
                                                        "font-size: 20px;\n"
                                                        "color: #800000;\n"
                                                        "text-align: center;\n"
                                                        "vertical-align: middle;\n"
                                                        )
                self.TenantInfoLabel.setObjectName("TenantInfoLabel")
                self.TenantInfoLabel.setAlignment(Qt.AlignCenter)

# ==========
#        BASE FRAME
# =========================



# =========================
#      TENANT INFO
# ==========

                self.InfoFrame = QtWidgets.QFrame(self.mainFrame)
                self.InfoFrame.setGeometry(QtCore.QRect(20, 90, 618, 310))
                self.InfoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.InfoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.InfoFrame.setObjectName("InfoFrame")

                self.gridFrame = QtWidgets.QGridLayout(self.InfoFrame)
                self.gridFrame.setContentsMargins(5, 5, 5, 5)  
                self.gridFrame.setHorizontalSpacing(4) 
                self.gridFrame.setAlignment(QtCore.Qt.AlignCenter)
                self.InfoFrame.setLayout(self.gridFrame)

                # ===========
                # Base info
                self.NameLabel = QtWidgets.QLabel(self.InfoFrame)
                self.NameLabel.setStyleSheet(   "background: none;\n"
                                                "border: none;\n"
                                                "color: #800000;\n"
                                                "font-family: \'Cal Sans\', sans-serif;\n"
                                                "font-weight: 700;\n"
                                                "font-style: normal;\n"
                                                "font-size: 14px;")
                self.NameLabel.setObjectName("NameLabel")

                self.NameLine = QtWidgets.QLineEdit(self.InfoFrame)
                self.NameLine.setObjectName("NameLine")
                self.NameLine.setFixedSize(450, 30)
                self.NameLine.setReadOnly(True)

                self.SexLabel = QtWidgets.QLabel(self.InfoFrame)
                self.SexLabel.setStyleSheet(    "background: none;\n"
                                                "border: none;\n"
                                                "color: #800000;\n"
                                                "font-family: \'Cal Sans\', sans-serif;\n"
                                                "font-weight: 700;\n"
                                                "font-style: normal;\n"
                                                "font-size: 14px;")
                self.SexLabel.setObjectName("SexLabel")

                self.SexLine = QtWidgets.QLineEdit(self.InfoFrame)
                self.SexLine.setObjectName("SexLine")
                self.SexLine.setReadOnly(True)
                # Base info
                # ===========

                # ===========
                # Contact info
                self.PhonNumLabel = QtWidgets.QLabel(self.InfoFrame)
                self.PhonNumLabel.setStyleSheet("background: none;\n"
                                                "border: none;\n"
                                                "color: #800000;\n"
                                                "font-family: \'Cal Sans\', sans-serif;\n"
                                                "font-weight: 700;\n"
                                                "font-style: normal;\n"
                                                "font-size: 14px;")
                self.PhonNumLabel.setObjectName("PhonNumLabel")

                self.PhoneLine = QtWidgets.QLineEdit(self.InfoFrame)
                self.PhoneLine.setObjectName("PhoneLine")
                self.PhoneLine.setReadOnly(True)

                self.EmailLabel = QtWidgets.QLabel(self.InfoFrame)
                self.EmailLabel.setStyleSheet(  "background: none;\n"
                                                "border: none;\n"
                                                "color: #800000;\n"
                                                "font-family: \'Cal Sans\', sans-serif;\n"
                                                "font-weight: 700;\n"
                                                "font-style: normal;\n"
                                                "font-size: 14px;")
                self.EmailLabel.setObjectName("EmailLabel")

                self.EmailLine = QtWidgets.QLineEdit(self.InfoFrame)
                self.EmailLine.setObjectName("EmailLine")
                self.EmailLine.setReadOnly(True)

                self.ECLabel = QtWidgets.QLabel(self.InfoFrame)
                self.ECLabel.setStyleSheet(  "background: none;\n"
                                                "border: none;\n"
                                                "color: #800000;\n"
                                                "font-family: \'Cal Sans\', sans-serif;\n"
                                                "font-weight: 700;\n"
                                                "font-style: normal;\n"
                                                "font-size: 14px;")
                self.ECLabel.setObjectName("ECLabel")

                self.ECLine = QtWidgets.QLineEdit(self.InfoFrame)
                self.ECLine.setObjectName("ECLine")
                self.ECLine.setReadOnly(True)
                # Contact info
                # ===========

                # ===========
                # Rents info
                self.RoomNumLabel = QtWidgets.QLabel(self.InfoFrame)
                self.RoomNumLabel.setStyleSheet(     "background: none;\n"
                                                        "border: none;\n"
                                                        "color: #800000;\n"
                                                        "font-family: \'Cal Sans\', sans-serif;\n"
                                                        "font-weight: 700;\n"
                                                        "font-style: normal;\n"
                                                        "font-size: 14px;")
                self.RoomNumLabel.setObjectName("RoomNumLabel")

                self.RoomLine = QtWidgets.QLineEdit(self.InfoFrame)
                self.RoomLine.setObjectName("RoomLine")
                self.RoomLine.setReadOnly(True)
                
                self.MoveStatusLabel = QtWidgets.QLabel(self.InfoFrame)
                self.MoveStatusLabel.setStyleSheet(     "background: none;\n"
                                                        "border: none;\n"
                                                        "color: #800000;\n"
                                                        "font-family: \'Cal Sans\', sans-serif;\n"
                                                        "font-weight: 700;\n"
                                                        "font-style: normal;\n"
                                                        "font-size: 14px;")
                self.MoveStatusLabel.setObjectName("MoveStatusLabel")

                self.MoveLine = QtWidgets.QLineEdit(self.InfoFrame)
                self.MoveLine.setObjectName("MoveLine")
                self.MoveLine.setReadOnly(True)
                # Rents info
                # ===========

                # ===========
                # Pays info
                self.PaymStatusLabel = QtWidgets.QLabel(self.InfoFrame)
                self.PaymStatusLabel.setStyleSheet(     "background: none;\n"
                                                        "border: none;\n"
                                                        "color: #800000;\n"
                                                        "font-family: \'Cal Sans\', sans-serif;\n"
                                                        "font-weight: 700;\n"
                                                        "font-style: normal;\n"
                                                        "font-size: 14px;")
                self.PaymStatusLabel.setObjectName("PaymStatusLabel")

                self.PayLine = QtWidgets.QLineEdit(self.InfoFrame)
                self.PayLine.setObjectName("PayLine")
                self.PayLine.setReadOnly(True)

                self.PaidLabel = QtWidgets.QLabel(self.InfoFrame)
                self.PaidLabel.setStyleSheet(     "background: none;\n"
                                                        "border: none;\n"
                                                        "color: #800000;\n"
                                                        "font-family: \'Cal Sans\', sans-serif;\n"
                                                        "font-weight: 700;\n"
                                                        "font-style: normal;\n"
                                                        "font-size: 14px;")
                self.PaidLabel.setObjectName("PaidLabel")

                self.PaidLine = QtWidgets.QLineEdit(self.InfoFrame)
                self.PaidLine.setObjectName("PaidLine")
                self.PaidLine.setReadOnly(True)

                self.RemainingLabel = QtWidgets.QLabel(self.InfoFrame)
                self.RemainingLabel.setStyleSheet(     "background: none;\n"
                                                        "border: none;\n"
                                                        "color: #800000;\n"
                                                        "font-family: \'Cal Sans\', sans-serif;\n"
                                                        "font-weight: 700;\n"
                                                        "font-style: normal;\n"
                                                        "font-size: 14px;")
                self.RemainingLabel.setObjectName("RemainingLabel")

                self.RemainLine = QtWidgets.QLineEdit(self.InfoFrame)
                self.RemainLine.setObjectName("RemainLine")
                self.RemainLine.setReadOnly(True)
                # Pays info
                # ===========

                # =========
                # Layout

                self.gridFrame.addWidget(self.NameLabel,        0, 0)
                self.gridFrame.addWidget(self.NameLine,         0, 1, 1, 4)

                self.gridFrame.addWidget(self.SexLabel,         1, 0)
                self.gridFrame.addWidget(self.SexLine,          1, 1)

                self.gridFrame.addWidget(self.PhonNumLabel,     1, 2)
                self.gridFrame.addWidget(self.PhoneLine,        1, 3)

                self.gridFrame.addWidget(self.EmailLabel,       2, 0)
                self.gridFrame.addWidget(self.EmailLine,        2, 1, 1, 2)

                self.gridFrame.addWidget(self.ECLabel,          7, 0)
                self.gridFrame.addWidget(self.ECLine,           7, 1)

                self.gridFrame.addWidget(self.RoomNumLabel,     3, 2)
                self.gridFrame.addWidget(self.RoomLine,         3, 3)

                self.gridFrame.addWidget(self.MoveStatusLabel,  3, 0)
                self.gridFrame.addWidget(self.MoveLine,         3, 1)

                self.gridFrame.addWidget(self.PaymStatusLabel,  4, 0)
                self.gridFrame.addWidget(self.PayLine,          4, 1)

                self.gridFrame.addWidget(self.PaidLabel,        5, 2)
                self.gridFrame.addWidget(self.PaidLine,         5, 3)

                self.gridFrame.addWidget(self.RemainingLabel,   4, 2)
                self.gridFrame.addWidget(self.RemainLine,       4, 3)

                # Layout
                # =========


# ==========
#      TENANT INFO
# =========================

                self.retranslateUi(Dialog)
                QtCore.QMetaObject.connectSlotsByName(Dialog)   

        def retranslateUi(self, Dialog):
                _translate = QtCore.QCoreApplication.translate
                Dialog.setWindowTitle(_translate(       "Dialog", "Dialog"))
                self.TenantInfoLabel.setText(_translate("Dialog", "Tenant Profile"))
                self.NameLabel.setText(_translate(      "Dialog", "Name: "))
                self.SexLabel.setText(_translate(       "Dialog", "Sex: "))
                self.PhonNumLabel.setText(_translate(   "Dialog", "Phone Number: "))
                self.EmailLabel.setText(_translate(     "Dialog", "Email: "))
                self.ECLabel.setText(_translate(        "Dialog", "Emergency Contact: "))
                self.RoomNumLabel.setText(_translate(   "Dialog", "Room Number: "))
                self.MoveStatusLabel.setText(_translate("Dialog", "Move Status: "))
                self.PaymStatusLabel.setText(_translate("Dialog", "Payment Status: "))
                self.PaidLabel.setText(_translate(      "Dialog", "Paid Amount: "))
                self.RemainingLabel.setText(_translate( "Dialog", "Remaining Due: "))

