# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Kristelle\Documents\CCC151-Group Project\MainUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1065, 794)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 70, 1021, 671))
        self.frame.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"border: 2px solid #800000;\n"
"border-radius: 6px;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.SearchLineEdit = QtWidgets.QLineEdit(self.frame)
        self.SearchLineEdit.setGeometry(QtCore.QRect(450, 20, 351, 21))
        self.SearchLineEdit.setObjectName("SearchLineEdit")
        self.SearchpushButton = QtWidgets.QPushButton(self.frame)
        self.SearchpushButton.setGeometry(QtCore.QRect(810, 20, 81, 21))
        self.SearchpushButton.setStyleSheet("background-color: #00796B;\n"
"color: white;\n"
"font-family: \"Cal Sans\", sans-serif;\n"
"font-weight: 500;\n"
"font-size: 16px;\n"
"border: none;\n"
"border-radius: 4px;\n"
"padding: 3px 6px;\n"
"")
        self.SearchpushButton.setObjectName("SearchpushButton")
        self.SearchField = QtWidgets.QComboBox(self.frame)
        self.SearchField.setGeometry(QtCore.QRect(300, 20, 151, 21))
        self.SearchField.setObjectName("SearchField")
        self.RefreshpushButton = QtWidgets.QPushButton(self.frame)
        self.RefreshpushButton.setGeometry(QtCore.QRect(900, 20, 81, 21))
        self.RefreshpushButton.setStyleSheet("background-color: rgb(255, 255, 253);\n"
"border: 1px solid #660000; \n"
"border-radius: 6px;\n"
"color: #00796B;\n"
"font-family: \"Cal Sans\", sans-serif;\n"
"font-weight: 500;\n"
"font-size: 14px;\n"
"padding: 3px 6px;\n"
"")
        self.RefreshpushButton.setObjectName("RefreshpushButton")
        self.AddpushButton = QtWidgets.QPushButton(self.frame)
        self.AddpushButton.setGeometry(QtCore.QRect(900, 630, 93, 28))
        self.AddpushButton.setStyleSheet("background-color: #388E3C; /* Darker green */\n"
"color: white;\n"
"font-family: \"Cal Sans\", sans-serif;\n"
"font-weight: 700; /* Bold */\n"
"font-size: 16px;\n"
"border: none;\n"
"border-radius: 4px;\n"
"padding: 6px 12px;\n"
"")
        self.AddpushButton.setObjectName("AddpushButton")
        self.EditpushButton = QtWidgets.QPushButton(self.frame)
        self.EditpushButton.setGeometry(QtCore.QRect(800, 630, 93, 28))
        self.EditpushButton.setStyleSheet("background-color: #1565C0; /* Darker blue */\n"
"color: white;\n"
"font-family: \"Cal Sans\", sans-serif;\n"
"font-weight: 700; /* Bold */\n"
"font-size: 16px;\n"
"border: none;\n"
"border-radius: 4px;\n"
"padding: 6px 12px;\n"
"")
        self.EditpushButton.setObjectName("EditpushButton")
        self.DeletepushButton = QtWidgets.QPushButton(self.frame)
        self.DeletepushButton.setGeometry(QtCore.QRect(120, 630, 93, 28))
        self.DeletepushButton.setStyleSheet("background-color: #C62828; /* Darker red */\n"
"color: white;\n"
"font-family: \"Cal Sans\", sans-serif;\n"
"font-weight: 700; /* Bold */\n"
"font-size: 16px;\n"
"border: none;\n"
"border-radius: 4px;\n"
"padding: 6px 12px;\n"
"")
        self.DeletepushButton.setObjectName("DeletepushButton")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget.setGeometry(QtCore.QRect(110, 60, 891, 561))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.TenantTable = QtWidgets.QTableWidget(self.page_1)
        self.TenantTable.setGeometry(QtCore.QRect(10, 10, 871, 541))
        self.TenantTable.setObjectName("TenantTable")
        self.TenantTable.setColumnCount(0)
        self.TenantTable.setRowCount(0)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.RoomTable = QtWidgets.QTableWidget(self.page_2)
        self.RoomTable.setGeometry(QtCore.QRect(10, 10, 871, 541))
        self.RoomTable.setObjectName("RoomTable")
        self.RoomTable.setColumnCount(0)
        self.RoomTable.setRowCount(0)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.RentTable = QtWidgets.QTableWidget(self.page_3)
        self.RentTable.setGeometry(QtCore.QRect(10, 10, 871, 541))
        self.RentTable.setObjectName("RentTable")
        self.RentTable.setColumnCount(0)
        self.RentTable.setRowCount(0)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.PaymentTable = QtWidgets.QTableWidget(self.page_4)
        self.PaymentTable.setGeometry(QtCore.QRect(10, 10, 871, 541))
        self.PaymentTable.setObjectName("PaymentTable")
        self.PaymentTable.setColumnCount(0)
        self.PaymentTable.setRowCount(0)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.EmergencyTable = QtWidgets.QTableWidget(self.page_5)
        self.EmergencyTable.setGeometry(QtCore.QRect(10, 10, 871, 541))
        self.EmergencyTable.setObjectName("EmergencyTable")
        self.EmergencyTable.setColumnCount(0)
        self.EmergencyTable.setRowCount(0)
        self.stackedWidget.addWidget(self.page_5)
        self.tenantPushButton = QtWidgets.QPushButton(self.frame)
        self.tenantPushButton.setGeometry(QtCore.QRect(10, 60, 91, 28))
        self.tenantPushButton.setStyleSheet("background-color: rgb(250, 255, 242); /* Soft light green background */\n"
"border: 1px solid #660000; /* Darker maroon border */\n"
"border-radius: 4px;\n"
"padding: 5px;\n"
"font-family: \'Roboto\', sans-serif;\n"
"font-weight: 500; /* Normal weight */\n"
"font-style: normal;\n"
"font-size: 13px;\n"
"color: #800000; /* Maroon text color */\n"
"")
        self.tenantPushButton.setObjectName("tenantPushButton")
        self.roomPushButton = QtWidgets.QPushButton(self.frame)
        self.roomPushButton.setGeometry(QtCore.QRect(10, 90, 91, 28))
        self.roomPushButton.setStyleSheet("background-color: rgb(250, 255, 242); /* Soft light green background */\n"
"border: 1px solid #660000; /* Darker maroon border */\n"
"border-radius: 4px;\n"
"padding: 5px;\n"
"font-family: \'Roboto\', sans-serif;\n"
"font-weight: 500; /* Normal weight */\n"
"font-style: normal;\n"
"font-size: 13px;\n"
"color: #800000; /* Maroon text color */\n"
"")
        self.roomPushButton.setObjectName("roomPushButton")
        self.rentPushButton = QtWidgets.QPushButton(self.frame)
        self.rentPushButton.setGeometry(QtCore.QRect(10, 120, 91, 28))
        self.rentPushButton.setStyleSheet("background-color: rgb(250, 255, 242); /* Soft light green background */\n"
"border: 1px solid #660000; /* Darker maroon border */\n"
"border-radius: 4px;\n"
"padding: 5px;\n"
"font-family: \'Roboto\', sans-serif;\n"
"font-weight: 500; /* Normal weight */\n"
"font-style: normal;\n"
"font-size: 13px;\n"
"color: #800000; /* Maroon text color */\n"
"")
        self.rentPushButton.setObjectName("rentPushButton")
        self.paymentPushButton = QtWidgets.QPushButton(self.frame)
        self.paymentPushButton.setGeometry(QtCore.QRect(10, 150, 91, 28))
        self.paymentPushButton.setStyleSheet("background-color: rgb(250, 255, 242); /* Soft light green background */\n"
"border: 1px solid #660000; /* Darker maroon border */\n"
"border-radius: 4px;\n"
"padding: 5px;\n"
"font-family: \'Roboto\', sans-serif;\n"
"font-weight: 500; /* Normal weight */\n"
"font-style: normal;\n"
"font-size: 13px;\n"
"color: #800000; /* Maroon text color */\n"
"\n"
"")
        self.paymentPushButton.setObjectName("paymentPushButton")
        self.emergencyPushButton = QtWidgets.QPushButton(self.frame)
        self.emergencyPushButton.setGeometry(QtCore.QRect(10, 180, 91, 31))
        self.emergencyPushButton.setStyleSheet("background-color: rgb(250, 255, 242); /* Soft light green background */\n"
"border: 1px solid #660000; /* Darker maroon border */\n"
"border-radius: 4px;\n"
"padding: 5px;\n"
"font-family: \'Roboto\', sans-serif;\n"
"font-weight: 500; /* Normal weight */\n"
"font-style: normal;\n"
"font-size: 13px;\n"
"color: #800000; /* Maroon text color */\n"
"\n"
"")
        self.emergencyPushButton.setObjectName("emergencyPushButton")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(30, 20, 1021, 51))
        self.frame_2.setStyleSheet("background-color: #800000;  /* Maroon background */\n"
"                border: 1px solid #660000;  /* Darker maroon border */\n"
"                border-radius: 4px;\n"
"                padding: 5px;\n"
"                font-family: \'Times New Roman\', serif;  /* Formal font */\n"
"                font-size: 14px;\n"
"                color: white;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(10, 10, 391, 31))
        self.label.setStyleSheet("background-color: rgb(250, 255, 242); /* Soft light green background */\n"
"border: 1px solid #660000; /* Darker maroon border */\n"
"border-radius: 4px;\n"
"padding: 5px;\n"
"font-family: \'Cal Sans\', sans-serif;\n"
"font-weight: 600;\n"
"font-style: normal;\n"
"font-size: 16px;\n"
"color: #800000; /* Maroon text color */\n"
"\n"
"")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1065, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SearchpushButton.setText(_translate("MainWindow", "Search"))
        self.RefreshpushButton.setText(_translate("MainWindow", "Refresh"))
        self.AddpushButton.setText(_translate("MainWindow", "Add"))
        self.EditpushButton.setText(_translate("MainWindow", "Edit"))
        self.DeletepushButton.setText(_translate("MainWindow", "Delete"))
        self.tenantPushButton.setText(_translate("MainWindow", "Tenant"))
        self.roomPushButton.setText(_translate("MainWindow", "Room"))
        self.rentPushButton.setText(_translate("MainWindow", "Rent Data"))
        self.paymentPushButton.setText(_translate("MainWindow", "Payment"))
        self.emergencyPushButton.setText(_translate("MainWindow", "Emergency"))
        self.label.setText(_translate("MainWindow", "Sistore Boarding House Management System"))
